### ISSUE TITLE
Create importing script in Moose Pharo Importer wizard broken

### ISSUE THREAD

**Issue by seandenigris** [moosetechnology/Moose#1026]
Originally reported on Google Code with ID 1026

```
When loading smalltalk code from the moosepanel.
There is a button on the first page of the wizard to create a script

But the script generated by this option does not work.
Possibly calling a method that no longer exist
```

Reported by `anquetil.nicolas` on 2013-12-09 19:27:58

**Comment by girba** [comment]
Name: Moose-Wizard-TudorGirba.107
Author: TudorGirba
Time: 9 June 2017, 10:29:01.303127 am
UUID: fc4b937f-e40d-0d00-9b18-320a02856aaa
Ancestors: Moose-Wizard-VincentBlondeau.106

do not use asLegalSelector anymore
