### ISSUE TITLE
Nonexistent MalCustomObjectTraverser referenced

### ISSUE THREAD

**Issue by seandenigris** [moosetechnology/Moose#1086]
Originally reported on Google Code with ID 1086

```
Object>>#deepGraph: from Moose-Algos-GraphObjectTraverser references nonexistent MalCustomObjectTraverser
```

Reported by `ukodrag` on 2014-09-15 08:10:31

**Comment by pavel-krivanek** [comment]
MalCustomObjectTraversal was in the frist version of Moose-Algos-ObjectTraverser. Then it was renamed to MalCustomObjectTraverser and redesigned. Because this method has its own package, has no senders and does not work for the long time, we can remove the package from the configuration.

**Comment by jecisc** [comment]
@pavel-krivanek 

Name: ConfigurationOfMooseAlgos-CyrilFerlicot.58
Author: CyrilFerlicot
Time: 13 April 2017, 10:31:42.155869 pm
UUID: 5d0821f3-7309-0d00-9a00-2be404e7b852
Ancestors: ConfigurationOfMooseAlgos-TudorGirba.57

- Add a common stable to not break builds in Pharo 6
- Add common development to not break builds before pharo 5
- New baseline removing obsolete Moose-Algos-GraphObjectTraverser

If this is fine for you we can close this issue.

**Comment by jecisc** [comment]
Weird. This is still loaded.

**Comment by jecisc** [comment]
Corrected.
