### ISSUE TITLE
PNG exporter with Roassal

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1128]
I found what the bug is in the png export: it does not consider the zoom. Run the script below, then click on the zoom or the fit-to-size button, then export. Zoom again and export again and it will be worse.

| b s p data |
data := { 
{'WP1.1' . 0 . 2}.
{'WP1.2' . 1 . 5}.
{'WP1.3' . 2 . 5}.
{'WP1.4' . 5 . 6}.
{'WP2.1' . 6 . 8}.
{'WP2.2' . 7 . 10}.
{'WP2.3' . 9 . 11}.
{'WP2.4' . 10 . 12}.
{'WP3.1' . 0 . 3}.
{'WP3.2' . 3 . 7}.
{'WP3.3' . 7 . 11}.
{'WP3.4' . 11 . 12}.
 }.
b := RTTimeline new.
s := RTTimelineSet new.
s objects: data.
s lineIdentifier: #first.
s start: #second.
s end: #third.
b add: s.
b axisX
    noDecimal;
    title: 'Quarters';
    numberOfLabels: 12.

p := RTHorizontalTimelineDecorator new.
p addLineAboveIdentifier: 'WP1.4'.
p addLineAboveIdentifier: 'WP2.4'.
p shape line width: 2; color: (Color black).
b addDecorator: p.

b build.
^ b view

**Comment by girba** [comment]
I think you need two ways of exporting. For large pictures, you want to export as it is. For smaller ones, you do want to export the zooming. So how about having a dialogue that allows us to set the zooming when exporting?

**Comment by bergel** [comment]
We have added two way to export PNG, one using the scale and one without using it.
![screenshot 2017-03-03 18 47 48](https://cloud.githubusercontent.com/assets/393742/23570205/fef9b5ea-0041-11e7-8028-e8e6b0094ffb.png)
