### ISSUE TITLE
Hook for Customized Presentation Constructors (e.g. Magritte)

### ISSUE THREAD

**Issue by seandenigris** [moosetechnology/Moose#1130]
Right now, by default, a presentation constructor must be an annotated method which takes a composite (and optional context) as arguments, and configures a presentation.

For example:
```
gtInspectorStepsIn: composite
	<gtInspectorPresentationOrder: 10> 
	composite list 
		title: 'Steps';
		display: [ self children ]
```

While this serves the basic purpose, I found myself continuously duplicating info which I had already described with Magritte, as in the description mirroring the above:
```
descriptionChildren
	<magritteDescription>
	^ MAToManyRelationDescription new
			accessor: #children;
			label: 'Steps';
			"..."
			yourself
```

So, playing around, I created the following general purpose hook to give more latitude in constructing presentations:
```
gtInspectorPresentationsIn: composite inContext: aGTInspector
			"..."
			eachPragma selector numArgs = 0
				ifTrue: [ 
					| configurationProvider |
					configurationProvider := self perform: eachPragma selector.
					configurationProvider gtPresentation cull: composite cull: aGTInspector cull: self ].
			"..."
```
This enables you to get presentations almost for free by leaning on (in this case) Magritte. The Magritte description gets a slight upgrade:
```
descriptionChildren
	<magritteDescription>
	<gtInspectorPresentationOrder: 10>
	^ MAToManyRelationDescription new
			accessor: #children;
			label: 'Steps';
			"..."
			gtPresentation: [ :a | a list ];
			yourself
```
#gtPresentation: sets default mappings, eliminating the original duplication:
```
gtPresentation: aBlock
	| wrapper |
	wrapper := [ :composite :context :subject |
		| presentation |
		presentation := aBlock cull: composite cull: context.
		presentation hasTitle ifFalse: [ presentation title: self label ].
		presentation transformation = presentation ifFalse: [ presentation display: (self accessor read: subject) ] ].
	self propertyAt: #gtPresentation put: wrapper
```

**Comment by seandenigris** [comment]
This was implemented with GT-Inspector-SeanDeNigris.307 (and 308) and then (I assume accidentally) removed with GT-Inspector-TudorGirba.413.

**Comment by seandenigris** [comment]
Fix in sthub/Moose/GToolkit - GT-Inspector-SeanDeNigris.428

**Comment by girba** [comment]
Please redo the change. I removed it intentionally because it introduces too much magic.

Another solution would be to have a trait that overrides gtInspectorPresentationsIn:inContext: and composes presentations differently. We are doing that in MooseEntity.

MooseEntity>>gtInspectorPresentationsIn: composite inContext: aGTInspector
	| pragmas |
	super gtInspectorPresentationsIn: composite inContext: aGTInspector.

	pragmas := Pragma 
				allNamed: #moosePresentationOrder: 
				from: self mooseInterestingEntity class 
				to: Object 
				sortedUsing: [: x :y | (x argumentAt: 1) < (y argumentAt: 1)].
	pragmas do: [ :eachPragma | 
		(eachPragma selector findTokens: $:) size = 1 
			ifTrue: [ self mooseInterestingEntity perform: eachPragma selector with: composite ]. 
		(eachPragma selector findTokens: $:) size = 2
			ifTrue: [ self mooseInterestingEntity perform: eachPragma selector with: composite with: aGTInspector ] ]

**Comment by girba** [comment]
Just to clarify: in the case of magritte it just happens that there is no argument in the pragma. However, in other situations this is not the case. So, we cannot distinguish between these cases in terms of number of arguments in the pragma. That is why we need a different solution.

**Comment by seandenigris** [comment]
I redid it (GT-Inspector-SeanDeNigris.428 in sthub/Moose/GToolkit). As far as being too much magic, how so? For one thing, that method seemed pretty magical already! I thought my change was incremental.

"in the case of magritte it just happens that there is no argument in the pragma" Oh! That may be part of the confusion. My code kicks in when _the containing method_, not the pragma, takes no arguments. AFAICT, presentation methods will either take one or two arguments (they must at least accept the composite), so wouldn't it make sense that a method taking no arguments would return something that could act as a presentation method?

**Comment by seandenigris** [comment]
Included in ConfigurationOfGTInspectorCore version 3.15
