### ISSUE TITLE
Applying class blueprint on multiple classes does not show interclass invocations

### ISSUE THREAD

**Issue by girba** [moosetechnology/Moose#1135]
If you load this MSE file, and spawn a Class Blueprint for both classes, the invocation will not appear.

( 
(FAMIX.Package (id: 2 )
  (name 'Package1'))
(FAMIX.Class (id: 3 )
  (name 'Class2')
  (parentPackage (ref: 2)))
(FAMIX.Class (id: 4 )
  (name 'Class3')
  (parentPackage (ref: 2)))
(FAMIX.Method (id: 5 )
  (name 'METHOD_1')
  (parentType (ref: 3)))
(FAMIX.Method (id: 6 )
  (name 'METHOD_1')
  (parentType (ref: 4)))
(FAMIX.Invocation
  (sender (ref: 5))
  (candidates (ref: 6))
  (signature 'DUMMY')))

**Comment by RainerWinkler** [comment]
Error still present in Moose 6.0

**Comment by badetitou** [comment]
Still present in Moose 7

**Comment by anneetien** [comment]
ClassBluePrint has been modified and focuses only on one class.
