### ISSUE TITLE
Can't load OSSubprocess

### ISSUE THREAD

**Issue by olivierauverlot** [moosetechnology/Moose#1138]
Hi,

I need to use OSSubprocess in a project with Moose 6. I just tried to load it in a new Moose 6 image but that's doesn't work.

VM: Mac OS - intel - 1092 - CoInterpreter VMMaker.oscog-eem.1726 uuid: 6a968923-b541-4573-bc4f-64fb95e6462d Mar 15 2016
StackToRegisterMappingCogit VMMaker.oscog-eem.1726 uuid: 6a968923-b541-4573-bc4f-64fb95e6462d Mar 15 2016
https://github.com/pharo-project/pharo-vm.git Commit: 2b53ae43e6a030759fbfa6ce8737a7f55ba76dd1 Date: 2016-03-15 19:05:06 +0100 By: Esteban Lorenzano estebanlm@gmail.com Jenkins build #576

Image: Pharo5.0 [Latest update: #50732]

UndefinedObject(Object)>>doesNotUnderstand: #waitTimeoutMSecs:
    Receiver: nil
    Arguments and temporary variables: 
        aMessage:   waitTimeoutMSecs: 1000
        exception:  MessageNotUnderstood: receiver of "waitTimeoutMSecs:" is nil
        resumeValue:    nil
    Receiver's instance variables: 
nil

OSSubprocess works fine in the latest Pharo 5 image. 

Someone has an idea ?

Olivier

**Comment by klaranosan** [comment]
We loaded OSSubprocess from the catalog (version 0.2.5) in Moose 6.1 on macOS and everything loaded perfectly. 
We suggest to close this entry.

The opendev team

**Comment by Ducasse** [comment]
Thanks
