### ISSUE TITLE
#atScope: not working with MooseOutgoingCompositeQueryResult

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1142]
I think that the #atScope: changed in Moose 6 but it seems that
MooseOutgoingCompositeQueryResult still uses the old #atScope.

To see the problem you can just copy this test in MooseQueryTest:

testProblemAtScope
    self shouldnt: [ class2 querySureOutgoingAssociations atTypeScope ]
raise: MessageNotUnderstood

**Comment by jecisc** [comment]
Apparently this (MooseOutgoingCompositeQueryResult) is not used anymore. It should be deprecated to be sure then removed.

**Comment by badetitou** [comment]
MooseOutgoingCompositeQueryResult has been deleted since Moose 6.1. 
I think we can close this issue
