### ISSUE TITLE
MooseMetaBrowser cannot be opened on general models

### ISSUE THREAD

**Issue by pavel-krivanek** [moosetechnology/Moose#1145]
MooseMetaBrowser expects that the metamodel elements have an implementing class and checks the class comment because of the color setting. See:

```
tower := FMTower new.
tower metamodel importString: FMHeinekenExample metamodelMSE.
tower model importString: FMHeinekenExample modelMSE.
MooseMetaBrowser new openOn: tower metamodel.
```

**Comment by pavel-krivanek** [comment]
Name: Famix-Core-PavelKrivanek.301
Author: PavelKrivanek
Time: 4 January 2017, 1:35:45.296807 pm
UUID: 8f989208-437e-4b20-9c7f-0105467d882d
Ancestors: Famix-Core-NicolasAnquetil.300

issue 1145: MooseMetaBrowser cannot be opened on general models

https://github.com/moosetechnology/Moose/issues/1145

**Comment by pavel-krivanek** [comment]
Name: Moose-Finder-PavelKrivanek.579
Author: PavelKrivanek
Time: 5 January 2017, 9:52:48.076811 am
UUID: f0d39d3d-f031-4122-807b-a0ed82323156
Ancestors: Moose-Finder-TudorGirba.578

issue 1145: MooseMetaBrowser cannot be opened on general models

#1145

**Comment by girba** [comment]
This issue is solved.
