### ISSUE TITLE
FMDomainCodeGenerator is not used and empty

### ISSUE THREAD

**Issue by pavel-krivanek** [moosetechnology/Moose#1146]
The class FMDomainCodeGenerator is not used in real (it has only one usage in test which checks its existence) and is empty. This class can be removed.

**Comment by pavel-krivanek** [comment]
Name: Fame-SmalltalkBinding-PavelKrivanek.12
Author: PavelKrivanek
Time: 5 January 2017, 4:29:36.831947 pm
UUID: 85102316-08d2-4bf2-9696-fa97abd7579e
Ancestors: Fame-SmalltalkBinding-MichelBany.11

Issue 1146: FMDomainCodeGenerator is not used and empty

- the class FMDomainCodeGenerator removed

**Comment by VincentBlondeau** [comment]
Actually, it is referenced in FMPublicInterfaceTest>>#publicInterface. So I readded it

**Comment by klaranosan** [comment]
Hi vincent

We checked and in Moose 6.1 there is not FMDomainCodeGenerator in FMPublicInterfaceTest>>#publicInterface.

Can we close this bug entry

The openDev team

**Comment by badetitou** [comment]
does not exist anymore
