### ISSUE TITLE
exampleElasticBoxZoom is not working properly

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1151]
The elastic zoom does not work. When trying to zoom a portion, it actually zoom a tiny part of the 
```
       | v |
	v := RTGrapherDecorationExample new exampleDeviation.
	v @ RTZoomableBoxView.
	^ v
```
![screen shot 2017-02-26 at 9 49 33 pm](https://cloud.githubusercontent.com/assets/393742/23345460/82006430-fc6d-11e6-8c75-ec9432f58167.png)

**Comment by akevalion** [comment]
Fixed, try last version of roassal
