### ISSUE TITLE
Clean the examples of Roassal

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1152]
Agree. Not only in Overall, in general with more than 4 figure previews at the same time, they became too small.

Cheers,

Hernán

2017-02-25 10:38 GMT-03:00 Ben Coman <btc@openinworld.com>:
Just some quick feedback... in the "Moose Suite 6.0 (beta)" image from PharoLauncher I opened World > Roassal > Roasasal Examples

Nice interface, but for the category "Grapher - Overall" I find there are too many items,
such that even the text labels are too small to read.  It might be better to split this out to a few more categories.

cheers -ben

**Comment by pavel-krivanek** [comment]
Moved to https://github.com/ObjectProfile/Roassal2/issues/16
