### ISSUE TITLE
Explora examples disappear out of view

### ISSUE THREAD

**Issue by bencoman** [moosetechnology/Moose#1153]
@bergel, Most of the explora examples have some problem with adjusting the viewport after expanding elements.

World > Roassal examples > Explora > CircularList 

Starts with one big circle. Right-Clicking on it ==> viewport is now blank. Translating the view up via left-drag finds two circles a page below. The circles are original size, so you can't see both ends of link at the same time. 

In addition, Left-Clicking the original single circle moves focus to a new inspector pane. 

Either the viewport should scale to the whole graph, but if there are many children each might end up too small to observe;   Or, scale viewport to the min of the x & y directions;   Or scale viewport to the sum length of the edges in the path from original to leaf node.

**Comment by pavel-krivanek** [comment]
Moved to https://github.com/ObjectProfile/Roassal2/issues/17
