### ISSUE TITLE
RTSelectionBox

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1156]
Should be available from the Menu in the playground

**Comment by klaranosan** [comment]
Hi alex 

Did you made progress on this issue? We are trying to clean the issues and you can help us to reduce the number of issues by closing the ones you know have been done or will not be done afterall.

The opendev teams

**Comment by pavel-krivanek** [comment]
Moved to https://github.com/ObjectProfile/Roassal2/issues/18
