### ISSUE TITLE
Restructure the menu

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1157]
The menu can be significantly improved. For example, having an export subfield, interaction...

![screenshot 2017-03-03 19 05 21](https://cloud.githubusercontent.com/assets/393742/23570724/5cf4b4a4-0044-11e7-8cfc-90809fe0fc9a.png)

**Comment by akevalion** [comment]
I change the menu to this
![image](https://cloud.githubusercontent.com/assets/10532890/23669431/e6380238-0342-11e7-9cd6-f45267bb1628.png)

**Comment by bergel** [comment]
Excellent!
