### ISSUE TITLE
Clicking on a submenu does not remove the submenu

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1164]
Clicking on a submenu leaves it open. For example, clicking on m2 / sm1 produces the following picture. Clicking on a submenu item should remove the submenu
![screenshot 2017-03-23 17 02 59](https://cloud.githubusercontent.com/assets/393742/24267957/c217e88c-0fea-11e7-8ae7-924989019246.png)

```
v := RTView new.
mb := RTMenuBuilder new view: v.
mb menu: 'm1' submenu: 'sm1' callback: [  ].
mb menu: 'm1' submenu: 'sm2' callback: [  ].
mb menu: 'm2' submenu: 'sm1' callback: [  ].
mb menu: 'm2' submenu: 'sm2' callback: [  ].
mb menu: 'm3' callback: [  ].
v
```

**Comment by akevalion** [comment]
I updated this in version Roassal2-akevalion.1556.

If the menu is not locked, all the submenus will hide
