### ISSUE TITLE
But with `RTDraggable`

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1166]
The following script does not work as expected. I would expect that dragging each blue circle moves _all the other blue circles._ This works only by dragging the first circle. Strange.
```
v := RTView new.
elements := RTEllipse new size: 20; elementsOn: (1 to: 20).
v addAll: elements.
RTGridLayout on: elements.

relevantElements := elements select: [ :e | e model < 10 ].
relevantElements do: [ :e | e trachelShape color: Color blue  ].

relevantElements @ (RTDraggable new groupToDrag: relevantElements).

v
```

A test `testGroupedDragAndDrop5` was added. This has to be fixed

**Comment by akevalion** [comment]
I updated a new version Roassal2-akevalion.1562 with the fix of this issue

**Comment by bergel** [comment]
Excellent! Works perfectly!
