### ISSUE TITLE
Bitmap seems to be flickering on Roassal on Windows

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1169]
Here is a mail except. We should try

```
	| v s c box |
	v := RTView new.
	c := v canvas.
	s := TRBitmapShape new.
	s form: RTIcon roassal.
	c addShape: s.
	box := (TRBoxShape new)
				extent: 50 @ 50;
				color: Color red.
	c addShape: box.
	box when: TRMouseDragging
		do: 
			[:evt |
			| pos |
			pos := evt canvas camera fromPixelToSpace: evt position.
			box translateTo: pos.
			c signalUpdate].
	v open
```

On Mar 30, 2017, at 12:45 PM, Bernd Elkemann <be@heeg.de> wrote:

Thank you for responding, and even so quickly (I could not do the same because I was just driving home).
This behavior appears on Visualworks 8.2 on Win10 (I only wrote Visualworks in the title, not the body).
I did not try different versions because our product has to release on at least 8.2.
Thank you for helping

On 30.03.2017 15:35, Alexandre Bergel wrote:
Hi Bernd,

Thanks for your nice words.

I cannot reproduce the problem you are describing. Consider this video:
https://dl.dropboxusercontent.com/u/31543901/TMP/VideoForBernd.mov

I made it on OS X, with the last version of Roassal on a very recent Pharo image.

What is your setting?

Cheers,
Alexandre

-- 
_,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:
Alexandre Bergel http://www.bergel.eu
^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;._,.;:~^~:;.

On Mar 30, 2017, at 8:51 AM, Bernd Elkemann (Georg Heeg eK) <be@heeg.de<mailto:be@heeg.de>> wrote:

Dear Roassal-Team

First of all, thank you for your work. Roassal is really impressive work.

At the moment I am working on some custom rendering using Trachel.

I have a rendering artifact with steps to reproduce attached to this e-Mail.

Description: When dragging a TRBoxShape and thus calling #signalUpdate, an unrelated BitmapShape is flickering. A rectangle of the bitmap's size (offset by half width and height) is shown and it has the color of the TRBoxShape (probably it uses the color of the most recent render).

Any help would be very welcomed

Greetings
Bernd Elkemann

<reproduce.st <http://reproduce.st>>

**Comment by bergel** [comment]
We are able to reproduce the problem on Windows. The bitmap is heavily flickering, in addition to have an extra colored box. On OS X there is no flickering problem however. We spent some time on understanding where the problem stems from. 

Unfortunately, we do not have a solution for that problem. VisualWorks uses an old version of Cairo and this may be the root of the whole issue. Maybe simply updating Cairo would remove the problem. But such an update is not trivial to do and will require quite some effort. We can have a look at this problem again, but not immediately.

**Comment by bergel** [comment]
Bernd Elkemann has worked on this issue.

Here is his email:
The workarounds I found are probably not what you want to put into the library, however they show what the problems are and hint at how to fix them.

First how i removed the additional box:

"Hack which has to be inserted after calling 'addShape: aTRBitmapShape' and before calling something else that renders in color. Without this, for each TRBitmapShape, an additional box will be rendered with dimensions of the bitmap, positioned at 0@0 and color of the last rendered color."
   | hackBox |
   hackBox := (TRBoxShape new)
               extent: 1 @ 1;
               strokeWidth: 0;
               color: Color transparent.
   c addShape: hackBox

Now to prevent the bitmap from flickering:

The problem is that it is calling Pixmap>>#cairoSurface for every bitmap for every render-frame during the drag-drop (or tick, if we decide to add animation).

The library tries to prevent this by having CairoContext>>cache. But the cache is not used because the CairoContext gets created for every frame.

We could work around this by making Surface>>#context like:
^context ifNil: [context:=CairoContext surface: self].
(Of course this would limit us to now only use one context per surface; for our purposes this is ok)

However, the Win32PixmapSurface gets created for every frame as well (the reasons seem complicated to me, set a breakpoint in Win32PixmapSurface class>>#new).

I temporarily fixed this (see attachments), however the solution is hacky because I dont understand how the Roassal architecture is supposed to work.

**Comment by bergel** [comment]
[https://dl.dropboxusercontent.com/u/31543901/TMP/Roassal2-full-changes.st](url)
[https://dl.dropboxusercontent.com/u/31543901/TMP/CairoGraphics-changes.st](url)

**Comment by akevalion** [comment]
I have added this sources to Roassal, It works well for some cases, but still I can see flickering:
* When I resize the window in TRVisual method extent:
* When I open an example in the inspector, can be related to the last point.

**Comment by bergel** [comment]
Thanks!
