### ISSUE TITLE
Action in Artwork should support undos

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1170]
This is important

**Comment by girba** [comment]
What is Artwork?

**Comment by bergel** [comment]
Artwork is a class of DataStudio, a new set of tools on top of Roassal.
This raise several questions: 
- Is DataStudio of interest of Moose? (I feel that yes)
- Should issues of Artwork be reported here?

**Comment by girba** [comment]
It is of interest, but it would be great to have its design to be more integrated with GT.

**Comment by bergel** [comment]
yes, but how?

**Comment by jecisc** [comment]
Not in moose anymore.
