### ISSUE TITLE
`RTCache` does not resize the bitmap

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1173]
Consider the following code. It does what is expected.
```
b := RTMondrian new.
b nodes: (1 to: 60).

b shape line color: (Color blue alpha: 0.2).
b edges connectToAll: (1 to: 60 by: 2) .
b layout force.
b build.

view := b view.
RTCache new cacheView: view.
view open
"
view inspect 
"
```

However, replacing `view open` by `view inspect`, then the picture is zoomed, which is rather ugly. 
I guess that the bitmap should be redone when camera is changing height.

**Comment by akevalion** [comment]
I have update RTCache because sometimes returns an Exception

**Comment by bergel** [comment]
Will not be fixed
