### ISSUE TITLE
Tests create noise

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1174]
I launched Moose tests in my image and at the end I have some noise.

I have a new package without repository called `MonticelloImporterResourcePackage`. 

I have Moose-Algo-Lattice that reformated two methods.

**Comment by klaranosan** [comment]
Hi,

we tried running the tests in Moose 6.1 and noticed the same thing.

The opendev team

**Comment by badetitou** [comment]
I do not notice the change with  Moose-Algo-Lattice.
Do you remember the modified methods?

**Comment by jecisc** [comment]
I fixed them in MooseAlgo I think.
