### ISSUE TITLE
Double>>round: is missing on VisualWorks

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1175]
You added the Pharo port of #round: to the Visualworks classes in the Number hierarchy in package Roassal2-Extentions. But #round: is missing for class Double in Visualworks in parallel to class Float, probably because Double doesn't exist in Pharo (?), only Float. So this leads to a mnu if Doubles are used as input.

**Comment by akevalion** [comment]
I have added an extention round: to Double in visualworks
