### ISSUE TITLE
MooseEntity>>children implementation is not correct. 

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1178]
For example it can select the parents. 

One idea would be to use TMetaLevelDependency higher in the hierarchy and to use it to return the children.

**Comment by girba** [comment]
Can you be more specific, please?

**Comment by badetitou** [comment]
The idea is to use trait TMetaLevelDependency directly at the level of MooseEntity.
I don't think they are sides effects?

**Comment by jecisc** [comment]
Currently, MooseEntity implementation is returning a set of everything returned by methods starting with #all and ending with a $s. 

This is really not stable. What if we don't have one of those methods for an entity?
What if we have a method #allParents?

Now each entity queriable should have a trait bringing a new version of the #children method.

I propose to remove this version from MooseEntity since it is really not a good implementation and since all subclasses with children should have a new version.
