### ISSUE TITLE
Something weird in the way fonts are looked up

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1183]
Consider the following code:
```Smalltalk
v := RTView new.
lbl := RTLabel new fontName: 'Bitmap DejaVu Sans'; elementOn: 'Hello World'.
v add: lbl.
v
```
It produces what is shown on the screenshot.

However, what is displayed is not DejaVu Sans. E.g., compare the "e" with https://www.fontsquirrel.com/fonts/dejavu-sans
![ejwvyesogyaqanc7sjdhhl_xgj2aiujarmhaugp696zv-t7igadyrww-5wqwhzp1scvjfcsszem9ndnex5spxxczy6pxbjybsbtccszbvcee5uarhqid18qtqm8wwdunnnusnbd_lcos-nqqplxsanm3ir4_wtuogw](https://cloud.githubusercontent.com/assets/393742/25142111/2351225c-243c-11e7-84e5-aee278e86782.png)

**Comment by bergel** [comment]
A bit more on the font.
```Smalltalk
font := FreeTypeFont fromFile: '/Library/Fonts/Bodoni Ornaments.ttf' pointSize: 42 index: 0.

morph := StringMorph contents: 'Hello World' font: font.

morph openInWindow 

```

**Comment by pavel-krivanek** [comment]
Moved to https://github.com/ObjectProfile/Roassal2/issues/22
