### ISSUE TITLE
Improve calendar

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1187]
Discussion on the mailing list:

I noticed that present visualization of week days start with Sunday as first day of week. E.g. in Europe/Germany weeks start on Monday (according ISO8601). We are visually so used to it, that other schemes make us think (not intuitive).

How could I modify this?

I will update RTCalendarBuilder to allow change the starting day

**Comment by akevalion** [comment]
I have updated the calendar builder, try the next example

`
| b |
Week startDay: #Monday.

b := RTCalendarBuilder new.
b dateShape composite: [ :com | 
	com add: (RTEllipse new color: [ :d | 
		d = Date today
			ifTrue: [ Color blue trans ]
			ifFalse: [Color transparent] ]; size: 18).
	com add: (RTLabel new text: [:d| d dayOfMonth];
		color: [:d | (d dayOfWeek = 1) 
			ifTrue: [Color red] 
			ifFalse: [ Color black ] ]) ].

b showDayNames.
b yearShape composite: [ :comp | 
	comp add: (RTLabel new text: [ :d | d year ]; height: 20 ).
	comp add: (RTBox new color: [ Color blue alpha: 0.1 ]). ] .
b dates: Year current.
b build.
^ b view
`
![foo](https://cloud.githubusercontent.com/assets/10532890/25518703/33871758-2bcb-11e7-8fbf-ff1284fc607b.png)

**Comment by bergel** [comment]
Excellent !
Thanks!
