### ISSUE TITLE
Horizontal bar chart is missing

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1194]
Currently, there is no way to have horizontal bar charts, as 
![ejwnzdsowyamanc7sbdmpghyg4tqygkwit2p6t2b9q3vaz53m4e5vkcczp0kme_tivkntdjkxfvbswizd4eqmk9ehopbawabshvcnogp7ughefmipkw_bvblbef9av65oqi9kamsdzthnb8_67onxa](https://cloud.githubusercontent.com/assets/393742/25474927/4fa295f2-2b35-11e7-8bef-b357c91b1910.png)

We need this!

**Comment by akevalion** [comment]
I have update roassal with RTHorizontalData
![foo](https://user-images.githubusercontent.com/10532890/27408399-55cac8c8-56aa-11e7-914b-6d38c5719351.png)
