### ISSUE TITLE
SourceAnchor>>isFile is a bad name

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1205]
Since we also have FAMIXFile as entity I find the name really bad. 
I would like to replace it by #isFileBasedAnchor or something like this.

**Comment by bergel** [comment]
Not Sure. `isFileBasedAnchor` is a very obscure method name. File based? What is an anchor?
The good thing of `isFile` is that it is easy to understand what it means.

**Comment by jecisc** [comment]
It is easy to understand but this is wrong. A FAMIXFileAnchor is *not* a file. It is a source anchor based on a file.
