### ISSUE TITLE
Add an industrial MSE export

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1213]
Actually there is some part of the MSE export taking time that could be reduce.

For example now we sort the attributes. I think we could just add the name first then the unsorted attributes in an industrial mode in the cases where the MSE will never be opened by an human. 

This could be a flag saved in a class attribute of the exporter.

**Comment by klaranosan** [comment]
Did you measure the cost of sorting the attributes because may this is negligible. 
We should profile this change to see if it is worth time. 

If someone wants to really investigate the cost of this changes, the sort behavior is located in the following method


FMRepositoryVisitor >> exportElement: each 
	
	| meta serial properties |

	meta := repository metaDescriptionOf: each.
	self flag: 'ideally, there should be no nil check here. Currently, we need it to accommodate the case in which we export a model based on a partial meta-model'. 
	meta ifNotNil: [
		serial := self indexOf: each.
		printer beginElement: meta fullName.
		printer serial: serial.
		properties := self sortAttributes: meta allAttributes.
		properties do: [ :property | 
			self 
				exportProperty: property
				for: each ].
		printer endElement: meta fullName
		].
	self increment. "UI stuff"

**Comment by klaranosan** [comment]
The sortAttributes method is indeed a bit circunvulated. 

sortAttributes: properties

	| names composites sorted |
	sorted := properties asArray sorted: [:n1 :n2 | n1 name < n2 name ].
	names := sorted select: [ :each | each name == #name ].
	composites := sorted select: [ :each | each isComposite ].
	^names, (sorted copyWithoutAll: (names union: composites)), composites

**Comment by jecisc** [comment]
I think it's too complicated for the gain for now.
