### ISSUE TITLE
Should FAMIXAssociation inherit from FAMIXSourcedEntity?

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1218]
I think FAMIXAssociation should not inherit from sourced entity. I should verify if the associations use the variables of FAMIXSourcedEntity. If they do not it's a great loss of memory.

**Comment by jecisc** [comment]
Some of them have sourceAnchors so yes it is good.

**Comment by girba** [comment]
Yes, this is needed. I want to extend this mechanism to allow us to map a FAMIX association with the AST produced by a parser from Moose.
