### ISSUE TITLE
#removeLastPopup does not work in VisualWorks

### ISSUE THREAD

**Issue by RebeccaMorganKSE** [moosetechnology/Moose#1221]
Roassal2.RTPopup class>>removeLastPopup leads to messageNotUnderstood in VisualWorks 8.2.1 when cursor is positioned over view canvas

**Comment by RebeccaMorganKSE** [comment]
Issue appears to have been resolved with clean image, can't reproduce in clean image.

**Comment by bergel** [comment]
Thanks Rebecca!

**Comment by RebeccaMorganKSE** [comment]
Unfortunately I've managed to replicate the issue in my clean image, it's appearing when the cursor is positioned over the view canvas after building a RTDynamicStackedGrapher. I've attached a screenshot of the error.
![popupbug - copy](https://user-images.githubusercontent.com/10083255/27465385-8c6253fc-5816-11e7-946c-142669934121.png)

**Comment by bergel** [comment]
Oh... We will work on it!

**Comment by akevalion** [comment]
This should be fixed in the last version of Roassal2-VisualWorks

**Comment by RebeccaMorganKSE** [comment]
It works perfectly now, thank you very much :-)

**Comment by bergel** [comment]
Thanks @RebeccaMorganKSE for your bug entry :-)
