### ISSUE TITLE
Layered TreeLayout does not align elements on the top

### ISSUE THREAD

**Issue by girba** [moosetechnology/Moose#1222]
Take a look at this script:
http://ws.stfx.eu/54G9IO1XX4R2

The issue is that instead of aligning the top left, it kind of centers the entities from the same layer.

This used to work properly, and the tree algorithm did not change. So something must have changed not too long ago related to translations.

**Comment by pavel-krivanek** [comment]
Moved to https://github.com/ObjectProfile/Roassal2/issues/29
