### ISSUE TITLE
Create Moose Playground

### ISSUE THREAD

**Issue by girba** [moosetechnology/Moose#1223]
Moose Panel is a limiting interface. We should build an input tool that merges a playground with the current Moose Panel functionality.

Also, the Moose Playground should rely on the inspector not on Moose Finder anymore.

**Comment by girba** [comment]
An initial version is available

Name: Moose-Finder-TudorGirba.591
Author: TudorGirba
Time: 9 June 2017, 11:19:37.095624 am
UUID: bed08534-e50d-0d00-9b1a-0d1102856aaa
Ancestors: Moose-Finder-TudorGirba.590

added MoosePlayground

**Comment by klaranosan** [comment]
MoosePlayground is now available in Moose 6.1.
We suggest to close this issue. 

The opendev team.

**Comment by Ducasse** [comment]
Thanks
