### ISSUE TITLE
Setting an inspection after having opened the view

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1224]
Consider the snippet:
```Smalltalk
v := RTView new.
v addMenu: 'Press me' callback: [ v add: (RTBox new size: 30; elementOn: 42). v signalUpdate ].
v
```
How can I make that the box is inspectable? I wish to click on the box and open a pane.

**Comment by girba** [comment]
This is something we needed to address since a long time.

**Comment by girba** [comment]
A related issue is #981

**Comment by jecisc** [comment]
Since we will have new interfaces in moose this is now obsolete.
