### ISSUE TITLE
MooseAbstractGroup>>allTypes is doing two time the same thing?

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1226]
I have the impression that we lose some time in allTypes. 

```smalltalk
MooseGroup
	withAll: ((self allWithSubTypesOf: FAMIXType ofGroupClass: FAMIXTypeGroup) )
	withDescription: 'All types'
```

I think that #allWithSubTypesOf:ofGroupClass already return a Moose group. I did not verified but if that's the case we could just remove the creation of another Moose group. This can be pretty long because of all the initialization of the MooseGroup.

**Comment by girba** [comment]
Name: Famix-Extensions-TudorGirba.306
Author: TudorGirba
Time: 11 June 2017, 2:36:24.622369 pm
UUID: af1ffd2f-100e-0d00-90b2-a2c401aa31b6
Ancestors: Famix-Extensions-CyrilFerlicot.305

fixed
https://github.com/moosetechnology/Moose/issues/1226

#1226
