### ISSUE TITLE
MNU while inspecting a Namespace

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1228]
I tried to inspect a namespace and I got: `Instance of FM3MetaDescription did not understand #title:`

It comes from:

```smalltalk
mooseFinderFameDescription: composite
	<moosePresentationOrder: 400>
	(self mooseDescription gtInspectorRelationsIn: composite)
		title: 'Fame';
		titleIcon: MooseIcons mooseFame
```

**Comment by VincentBlondeau** [comment]
Solve be solved with 
Name: Fame-Core-TudorGirba.55
Author: TudorGirba
Time: 10 June 2017, 10:46:57.446913 pm
UUID: b1027bec-020e-0d00-9b1c-787702856aaa
Ancestors: Fame-Core-CyrilFerlicot.54

improved the gt inspector integration
