### ISSUE TITLE
We need a way to not have overlapped elements

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1231]
There are some existing algorithms:
http://www.sciencedirect.com/science/article/pii/S0020025507000989
http://rp-www.cs.usyd.edu.au/~visual/valacon/pdf/papers/APVIS05-UsingSpringToRemoveNodeOverlapping.pdf

We need a solution for this. It is a recurrent complain.

**Comment by pavel-krivanek** [comment]
Moved to https://github.com/ObjectProfile/Roassal2/issues/31
