### ISSUE TITLE
FishEye has a bug

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1232]
Consider the example:

```Smalltalk
   |v|
    v := RTLayoutExample new exampleForce.
    v @ (RTFisheye radius: 50).
    ^ v
```

The zoom does not happens at the place where the mouse cursor is...

**Comment by bergel** [comment]
Another example:
```Smalltalk
b := RTMondrian new.
b nodes: (1 to: 9) forEach: [ :v |
	b nodes: (50 to: 150).
	b layout grid ].

b shape line color: Color red; withShorterDistanceAttachPoint.
b edges 
	connectFrom: [ :nb | nb + 2 // 5 ].

b layout force charge: -5000.
b view @ (RTFisheye radius: 120).
b
```

**Comment by akevalion** [comment]
I have update roassal with The solution for this issue,
RTFisheye plays with the extent and position of the elements. But this do not interact with the pixels of this view
<img width="230" alt="captura de pantalla 2017-06-21 a la s 18 00 59" src="https://user-images.githubusercontent.com/10532890/27408668-cb179c54-56ab-11e7-9bd6-e6797e5f54a9.png">
