### ISSUE TITLE
Use an attach point on any element

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1233]
We need to define a method ``RTAttachPoint on: someRoassalElements``
We should be cautious to not break some tests

**Comment by akevalion** [comment]
There is two new methods en RTAttachPoint
- **#on:**      accept one element or a collection of elements.
- **#on:thenDo:**     an utility method to modify the attacpoint attributes.

Also there is a new class **RTDualAttachPoint**. It allows to combine different attach points

<img width="1150" alt="captura de pantalla 2017-07-10 a la s 21 55 59" src="https://user-images.githubusercontent.com/10532890/28047806-b1baea5e-65ba-11e7-92e1-ba20be616c9f.png">

**Comment by bergel** [comment]
Okay, thanks!
