### ISSUE TITLE
Text is not centered for very small font size

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1240]
```Smalltalk
b := RTMondrian new.
b shape labeledBox
    borderColor: Color black;
    textHeight: 2.
    
b nodes: (1 to: 10).
b
```
![screenshot 2017-06-21 10 00 08](https://user-images.githubusercontent.com/393742/27388145-ae8586fc-5668-11e7-9cb3-a7ddd20dcbe6.png)

Probably it is a problem of `asIntegerPoint` somewhere

**Comment by pavel-krivanek** [comment]
Moved to https://github.com/ObjectProfile/Roassal2/issues/33
