### ISSUE TITLE
Spotter bug when selecting implementor from preview

### ISSUE THREAD

**Issue by lukego** [moosetechnology/Moose#1248]
Here is a Spotter bug that I can reliably reproduce in the Pharo 6.0 image.

Steps to reproduce:
1. Open spotter.
2. Enter a selector.
3. Choose an entry from `#Message`.
4. Click on the Preview arrow.
5. Click on an implementor in the preview.

Now comes an error `#isSelected: was sent to nil`.

Screenshot immediatley before clicking to trigger the bug:

<img width="1088" alt="screenshot 2017-07-18 11 46 14" src="https://user-images.githubusercontent.com/13791/28311214-38b4c72e-6baf-11e7-934f-0b8fc8c4d0ae.png">

Then immediately after triggering the bug:

<img width="1088" alt="screenshot 2017-07-18 11 46 35" src="https://user-images.githubusercontent.com/13791/28311228-44dd3ff4-6baf-11e7-8b31-e5b48d87d951.png">

**Comment by klaranosan** [comment]
Hi,

we tried reproducing the problem in pharo 6.0 and we got the same bug. We are wondering if this bug entry belongs here, it seems to be a general problem of pharo, not just moose.

The opendev team

**Comment by jecisc** [comment]
Sometimes there are some Pharo issues reported here because most of the team that created GlamourToolkit (including the spotter) is in the Moose community.

**Comment by badetitou** [comment]
The bug has been fixed in Pharo 7.0.
It do not think it will be fixed for Pharo 6.0
