### ISSUE TITLE
How to make a custom "Playground"?

### ISSUE THREAD

**Issue by lukego** [moosetechnology/Moose#1249]
Help please! :-)

I would like to make a custom version of the Playground. The script will be in another language, not Smalltalk. The "Go" button will run the script as an external program (OSProcess) and then present the results. The results will include both the output and some files.

So I need to extend the GTInspector...

1. Present a text area to enter a script, like Playground, with a "Go" button.
2. "Go" should spawn an OSProcess to run the script.
3. OSProcess should be automatically inspected (showing output.)
4. On completion should inspect the output directory.

Just wondering... How? :-)

Should I subclass Playground? Or make a new stripped down sibling class? Or is there already something else that is more similar to my use case?

Once the OSProcess finishes how can it signal that the Inspector should open its output? (Is this done with Announcer somehow?)

What is the most relevant documentation for this kind of thing?

Any help would be much appreciated... :)

**Comment by lukego** [comment]
Closing because I stumbled on

```
self new  openOn: GLMBasicExamples
```

and now I have examples coming out of my ears.

Curious: What is the expected way for users to discover this? (Some documentation? via the Spotter? the package browser? via Pharo tools/conventions for making examples available?)

**Comment by SergeStinckwich** [comment]
You have a GTExamples menu in Tools.

**Comment by lukego** [comment]
@SergeStinckwich Thanks for the tip.

Just as a newbie it's hard to know what my entry-point for discovery should be... the world menu? the spotter? the books/chapters on the internet? the help text included in the image? etc.

**Comment by lukego** [comment]
One more thing I am scratching my head about just now.

I can copy-paste-tweak some example code into a Playground like:

```
GLMCompositePresentation new list; table; tree; yourself.
```

but in the `Live` tab it always looks blank.

I think that I am missing one step, where I have to give it an object to operate on, but I am not really sure which message this should be... `openOn:`, `startOn:`, `entity:`, etc. Generally it's not transparent to me yet how the Examples are being initialized and where all those numbers in them come from.

**Comment by bergel** [comment]
Hi Luke,

I do not have an answer to your question, but I wanted to say that your effort is very valuable. 
We do have exactly the very same need.

**Comment by lukego** [comment]
Thanks @bergel. It's nice to hear :). Often it feels like things are obvious to everybody except me...

**Comment by lukego** [comment]
@SergeStinckwich btw I don't have that menu item in the standard Pharo 6 image. Maybe I need the Moose image for that. That's a bit inconvenient though because I'd prefer to work in the same image where I have my own application.

**Comment by lukego** [comment]
I'll reopen this issue and keep the stream of consciousness going just in case it leads to some useful discussion :).

I have the first part working now it seems: a text area where code can be entered and a "Go" button that runs an action.

```
| composite |
composite := GLMCompositePresentation new.
composite title: 'Script editor'.
composite text.
composite
	act: [ Transcript show: 'Click!'; cr. ]
	iconName: #glamorousGo
	on: $G
	entitled: 'Run'.
composite openOn: ''.
```

I was confused for quite a while because the "Go" button was not appearing when I look at the presentation in the "Live" tab of the inspector. So I thought that I was sending the `#act:iconName:on:entitled: message` wrong somehow. But then the button appeared when I did `openOn:` to get a new window and so I suppose the code is okay and it is a quirk of the inspector to not show the button (?).

The next step is to make the `Go` button cause the inspector to look at a new object to the right...

**Comment by lukego** [comment]
Side-note: I have not been able to download the Moose image yesterday or today. I assume it's because of the scheduled upgrade work on Inria CI/Jenkins taking longer than expected.

**Comment by lukego** [comment]
Just now I am all tangled up in understanding the relationships between Glamour browsers in general, the GTInspector that has the nice "tabbed miller columns" left-to-right flow, and the Playground that is superficially similar to my application in that it starts with a place to enter code.

There are a lot of concepts: browsers, presentations, panes, ports, transmissions, actions, etc. I am having a hard time internalizing these. I am also not sure how relevant they are: if I use the GTInspector as my front-end ("browser"?) then most of this stuff is probably hard-coded and I only need to work out how to do simple things like say that an object should be selected.

So that's what I am working on now... How to tell the inspector that an object is selected and should be shown to the right...

**Comment by lukego** [comment]
So I have my script editor based on the code above:

<img width="431" alt="screenshot 2017-07-19 11 55 19" src="https://user-images.githubusercontent.com/13791/28361466-291ecf1a-6c79-11e7-99c2-f4bd90cc0a34.png">

and clicking the green button is running my block. This part is great. The trouble is that I have _absolutely no clue_ how to make the green button do what I actually want, which is to create a new object (an OSProcess that runs the script) and inspect that to the right.

I suspect that my mental model is completely inside out, and I have the whole flow of data through transmissions etc mixed up, but after a couple of hours digging through code in the image I am ready to jump off a bridge :).

I'll leave this part aside for now and work on the inspector presentation for the OSProcess, on the assumption that sooner or later I will succeed in making the green button kick this off.

Tips would be so, so, so very welcome :).

**Comment by lukego** [comment]
Specifically the tip I would love is how to update this example:

```
| composite |
composite := GLMCompositePresentation new.
composite title: 'Script editor'.
composite text.
composite
	act: [ Transcript show: 'Click!'; cr. ]
	iconName: #glamorousGo
	on: $G
	entitled: 'Run'.
composite openOn: ''.
```

So that (say) clicking the green button takes the contents of the text box, applies a function to it (e.g. convert to upper case), and inspects that in a miller column to the right.

**Comment by lukego** [comment]
Replacing this long rambling issue with small neat ones...
