### ISSUE TITLE
How to trigger a new selection for the GTInspector?

### ISSUE THREAD

**Issue by lukego** [moosetechnology/Moose#1251]
I have a presentation that looks like this:

<img width="431" alt="screenshot 2017-07-19 11 55 19" src="https://user-images.githubusercontent.com/13791/28373936-99258874-6ca3-11e7-8aed-e2bea5ce0b2e.png">

and I am looking for a way to make the "Go" button (green arrow) send the text to a block and inspect the value in a miller-column to the right. (That is: to act like the Go button in the Playground except that this text is not Smalltalk code.)

Here is the current code:

```smalltalk
| composite |
composite := GLMCompositePresentation new.
composite title: 'Script editor'.
composite text.
composite act: [] iconName: #glamorousGo on: $G entitled: 'Run'.
composite openOn: ''.
```

What should I replace the empty block `[]` to process the text and inspect the result?

(This issue is a spin-off from #1249.)

**Comment by bergel** [comment]
No idea about the answer. But I am very interested in the result of your experiment. And if you can plug a syntax highlighter, ...

**Comment by girba** [comment]
Please use the mailing list for questions like these. The issue tracker should be for things developers should address.

**Comment by lukego** [comment]
Thanks for the pointer! Posting there instead...
