### ISSUE TITLE
ci.inria.fr/moose down?

### ISSUE THREAD

**Issue by fniephaus** [moosetechnology/Moose#1252]
e.g. https://ci.inria.fr/moose/job/moose-6.1/lastSuccessfulBuild/artifact/moose-6.1.zip

**Comment by jecisc** [comment]
The CI is back.

**Comment by lukego** [comment]
The Moose image download link is not working for me. I get asked for a login and then denied permission. I tested with an "Incognito" window so I don't think it's due to a cookie.

Clicking this link: https://ci.inria.fr/moose/job/moose-6.1/lastSuccessfulBuild/artifact/moose-6.1.zip

**Comment by jecisc** [comment]
This is working for me.

**Comment by girba** [comment]
It works for me as well.

**Comment by fniephaus** [comment]
Doesn't seem to work for me :(

**Comment by girba** [comment]
I tried the URL from a new browser (one that does not have my credentials), and indeed the download does not work. In fact, accessing the whole Jenkins requires a login now.

Does anyone know how to make Jenkins available for everyone in readonly mode?

I reopened the issue.

**Comment by jecisc** [comment]
It already should be the case because the moose CI has the "public" tag on Inria's infrastructure. Maybe we should contact inria's support.

**Comment by jecisc** [comment]
Maybe it is configurable in the Configure Global Security -> Access Control -> Security Realm but I am not sure.

**Comment by fniephaus** [comment]
[smalltalkCI](https://github.com/hpi-swa/smalltalkCI) uses those links, so all Moose builds on TravisCI and AppVeyor currently fail.

**Comment by girba** [comment]
Not only that, but the official download of moose 6.1 goes through the CI

**Comment by girba** [comment]
Ok, I fixed it now through `Configure Global Security`. Please confirm.

**Comment by fniephaus** [comment]
Works like a charm. Thanks!
