### ISSUE TITLE
Error While Load MSE File

### ISSUE THREAD

**Issue by willy-juisan** [moosetechnology/Moose#1253]
I was new to moosetechnology, and I start with the first example from [moosebook](http://themoosebook.org/book/index.html), but I encounter some error when I load the .mse file to moose. It prompt me two error: first was "Invalid utf8 input detected", the second was "Improper store into indexable object". I choose to proceed, and I continue to next step. But when I arrived at step where I should investigate one of the deprecated classes and select to view the source code, I got another error: "should provide specific implementation, it is usually easy!". 
Does somebody know how to fix this error? I was using windows 7 machine, moose 6.1, PharoV50.sources, jdt2famix-bin-1.0.3. I also attached the error screenshot below: 
Please help me @girba (I attend your session at SA Conference 2017 at NYC, and you encourage me to try this technology, so I hope you could help me).
![invalid utf8](https://user-images.githubusercontent.com/10928712/28492726-907a23d8-6f32-11e7-846a-298f26092106.PNG)
![should provide specific implementation](https://user-images.githubusercontent.com/10928712/28492727-907f0b1e-6f32-11e7-9297-8901ceed4797.PNG)
![improper store](https://user-images.githubusercontent.com/10928712/28492728-908824d8-6f32-11e7-9d30-e69c2c4a8dba.PNG)

**Comment by jecisc** [comment]
I included in FAMIX a version of Zinc with a feature to detect the encoding of a file this week. It should be used by Fame while reading MSE.

**Comment by willy-juisan** [comment]
Thanks @jecisc, that was the fastest response I ever got, really appreciate it. So I should wait for jdt2famix update next week to solve this error?..

**Comment by jecisc** [comment]
I will probably not have time to check it this weekend, maybe Doru will.

Just by curiosity, what is the encoding of your mse?

**Comment by willy-juisan** [comment]
Where could I check it? Sorry, all this stuff was really new for me..

**Comment by jecisc** [comment]
https://stackoverflow.com/questions/3710374/get-encoding-of-a-file-in-windows

You can try this on ArgoUML-0-34.mse

**Comment by willy-juisan** [comment]
I have tried it, and it was ANSI as show below screenshot: 
![image](https://user-images.githubusercontent.com/10928712/28492891-8d192920-6f35-11e7-99eb-4ced90297da9.png)

**Comment by jecisc** [comment]
Oh, I see that this is a known issue in jdt2famix: https://github.com/feenkcom/jdt2famix/issues/20

**Comment by willy-juisan** [comment]
I see.. so it was already a known issue in jdt2famix repo.. But how about the other two errors? Are they also show up because of this encoding issue?..

**Comment by jecisc** [comment]
Probably because PP2 is a parser and the last one is alos the reading of the MSE.

**Comment by willy-juisan** [comment]
Ok, I will wait for next release of jdt2famix, and try it again to see if the other two errors were also solved or not.. I will update it here.. Thanks again @jecisc

**Comment by willy-juisan** [comment]
Hi @jecisc, I just tried to use notepad to convert my mse file to utf8 encoding, just like the stackoverflow link you gave me (https://stackoverflow.com/questions/3710374/get-encoding-of-a-file-in-windows).. Now it could loaded without complaining invalid utf8 input, also the improper store object also dissapear.. But the error "should provide specific implementation, should be easy!" still appears everytime I tried to view the source code of a class.. Any idea what could cause this problem?.. I'm pretty sure this problem not related with the invalid utf8 encoding..

**Comment by badetitou** [comment]
It was fixed there: https://github.com/feenkcom/jdt2famix/pull/45
