### ISSUE TITLE
Strokewidth rendering incorrectly in HTML export

### ISSUE THREAD

**Issue by RebeccaMorganKSE** [moosetechnology/Moose#1258]
I've encountered an issue when exporting views to HTML from the inspector, the strokewidth for bordered ellipse shapes is too large (2*ellipse size), leading to overly large shapes. I believe that this function in the associated JS file is responsible:

setStrokeWidth: function(w){
   this._super(w*this.rectangle.width());
},
I believe it's a minor typo and should be something like:
setStrokeWidth: function(w){
   this._super(w, this.rectangle.width());
},
I've changed it locally, in my image, and it's working well :-) I'm using VisualWorks.

**Comment by jecisc** [comment]
Hi, this is the repo of the Pharo Moose repository. We do not manage the VisualWorks version. 
Have a nice day.
