### ISSUE TITLE
RTConstraint instance variables names swapped

### ISSUE THREAD

**Issue by jacksonzche** [moosetechnology/Moose#1260]
```
#fix: aFixedElement
	movableElement := aFixedElement
#movable: aMovableElement
	fixedElement := aMovableElement

```
The behaviour appears to be correct using #fix: and #movable: as separate message sends. Whereas:

```
#movable: aMovableElement fix: aFixedElement
	fixedElement := aFixedElement.
	movableElement := aMovableElement

```
Assigns to the correctly named instance variables, but doesn't work as expected when positioning. Appears the corresponding movableElementX, moveableElementY etc. names are also swapped.

**Comment by jecisc** [comment]
Roassal issues should be reported here: https://github.com/ObjectProfile/Roassal2

But I sent the link in the roassal discord chanel so that the information is not lost.
