### ISSUE TITLE
FAMIX should not load Hismo by default

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1264]
Hismo should be in its own project or group. The default configuration of FAMIX should probably not load it and it should be the configuration of Moose that choose to load it because most of the time we do not want it when we analyze an application.

**Comment by jecisc** [comment]
Done

**Comment by VincentBlondeau** [comment]
So, what have you done?

**Comment by jecisc** [comment]
We now have a group #Hismo in the ConfigurationOfFamix (IMO it would have been better to have a full configuration but Stephan Eggermont desagreed). 
We can load FAMIX with or without Hismo. 

In moose it loads FAMIX with hismo. In Synectique's tools for example we load it without Hismo. 

Later I will also cut the famix in smaller groups to have a group "core", "smalltalk", "java", "c" etc.

**Comment by girba** [comment]
Please revert this change :). Groups are terrible to manage and debug in Metacello especially when we have deep nesting. If we want it separately, then we make a separate configuration for it.

**Comment by girba** [comment]
I just did.

**Comment by jecisc** [comment]
Done.

**Comment by VincentBlondeau** [comment]
Done = Create ConfigurationOfHismo and load it by default in Moose ?

**Comment by jecisc** [comment]
Now there is a ConfigurationOfHismo referenced in ConfigurationOfMoose

**Comment by bergel** [comment]
I am wondering... Why not to have a kind of plugin mechanism, as we have in Roassal. Plugins can be accessible from the world menu. If Hismo is buried in the catalog, or worse, only in smalltalkhub, then this is not good...

**Comment by jecisc** [comment]
@bergel Hismo is still in Moose. Just not in the configuration of famix. That way we can load Famix and fame without project on top. This is useful to optimize industrial applications on top of Moose because it reduce the size of the meta model and by extension the navigation of generic algorithms.
