### ISSUE TITLE
Sankey diagram is not readable using the white theme

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1266]
![screen_shot_2017-10-05_at_09 41 50](https://user-images.githubusercontent.com/393742/31237427-534e5cd8-a9cd-11e7-85be-21b8bcf88f2e.png)

**Comment by akevalion** [comment]
I have updated the example of sankey with colors that work in white and dark theme.

White Theme

![foo](https://user-images.githubusercontent.com/10532890/31465011-13d07c22-aea9-11e7-9a15-ec555af4be75.png)

Dark Theme

![foo](https://user-images.githubusercontent.com/10532890/31465114-58556d4e-aea9-11e7-9e9f-2979426adec2.png)

Please tell me what do you think about it

**Comment by SergeStinckwich** [comment]
Looks nice, especially with the white theme !

**Comment by Ducasse** [comment]
So why don't you close the issue? Is it done? 
Why should it be me that have to clean the issue. There is not happening magically?
So I close it because it looks like it is done.
