### ISSUE TITLE
Using Foreign objects when exporting SVG

### ISSUE THREAD

**Issue by bergel** [moosetechnology/Moose#1273]
Dusty on Discord suggested to use foreign objects. He says:
"creating SVG for web interfacces, like I'm doing the graphical rendering in roassal, but exporting the SVG to a web interface. I'd like to make the blocks clickable (via <a ...> tag) to open properties of the item in the web app"
"also, forienobject would allow for title= or <title> tag for hover"

We should have a look at this.

**Comment by pavel-krivanek** [comment]
Moved to https://github.com/ObjectProfile/Roassal2/issues/37
