### ISSUE TITLE
Running example installation produces MetacelloConflictingProjectError

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1276]
To reproduce:
1. Go to http://moosetechnology.org/#install
1. Download the three zip files, as explained
1. Unpack all files
1. Drag `moose-6.1.image` onto `Pharo.exe`
1. Left-click on the empty desktop, select Moose > Moose Playground (this step needs more detailed instructions for absolute beginners, by the way)
1. Paste the following code (taken from the web site) into the editor
    ```
    Metacello new
        smalltalkhubUser: 'Moose' project: 'Moose';
        configuration: 'Moose';
        version: #development;
        load.
    ```
1. Click on the green Play icon

![screenshot](https://user-images.githubusercontent.com/3233724/34467507-8cc1e28e-eef4-11e7-875a-0609950d3b5d.png)

MetacelloConflictingProjectError: Load Conflict between existing BaselineOfStateSpecs [baseline] from github://dionisiydk/StateSpecs:v2.4.x and ConfigurationOfStateSpecs stable from http://www.smalltalkhub.com/mc/dionisiy/StateSpecs/main

**Comment by girba** [comment]
First, the moose-6.1. image is already up-to-date. You can just use it without loading the code again (skip steps 6 and 7)

**Comment by rillig** [comment]
In that case, the installation instructions on the web site should be a little clearer. Right now they are minimalistic and therefore misleading, as you saw in my case. A few explaning words here and there might also help other newbies. Just mention that using the image and the beta are _alternatives_, since that is not clear from the layout alone.
