### ISSUE TITLE
Remove "No help, sorry." tooltips

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1277]
When an exception is thrown while using Moose, an error window opens. The Abandon, Debug and Report buttons have tooltip that say `No help, sorry.`.

These tooltips serve no purpose and should therefore be removed. Even more, they create frustration since when I see a tooltip, I expect some helpful information. `No help, sorry.` is not helpful at all.

**Comment by Ducasse** [comment]
Do you have a screen shot and a reproducible case because right now I cannot really understand.

**Comment by rillig** [comment]
![image](https://user-images.githubusercontent.com/3233724/37556144-e5842f66-29f1-11e8-8f07-b4c9b6515aec.png)

To reproduce:
* Go to http://moosetechnology.org/#install
* Follow the instructions from the section "Moose 6.1 beta image"
* Start that image
* In the Moose Playground window, run the code from the "Moose 6.1 beta code" section

**Comment by rillig** [comment]
It's probably not a Moose bug but a Pharo one, but as a newbie I cannot tell the difference.

**Comment by jecisc** [comment]
This is a Pharo issue. I'll open an issue later on Pharo tracker and close this one once done. (Currently on phone)

**Comment by estebanlm** [comment]
> On 17 Mar 2018, at 15:09, CyrilFerlicot <notifications@github.com> wrote:
> 
> This is a Pharo issue. I'll open an issue later on Pharo tracker and close this one once done. (Currently on phone)
> 
no is not.
tat says there is a conflict between two versions of a baseline (installed and incoming).

typically you workaround the issue by adding 

onConflict: [ :e | e useLoaded ] 

(or e useIncoming)

to your metacello script.

Esteban

**Comment by jecisc** [comment]
Esteban, I was taking about the useless tooltip. Not the configuration conflict.

**Comment by estebanlm** [comment]
“no help, sorry”… why? Is very useful! ;)

**Comment by jecisc** [comment]
https://pharo.fogbugz.com/f/cases/21613/Pre-debugger-buttons-should-have-meaningful-tooltips

**Comment by jecisc** [comment]
Correction inbox. This should be corrected in the next Pharo version.
