### ISSUE TITLE
Web site: incomplete instructions in The Moose Book

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1278]
At http://themoosebook.org/book/index.html, there is this paragraph:

> This leaves us with 11 classes …

At this point, I as a complete newbie have no idea how to reach the panel with the 11 classes. I only have a panel with 14 classes, so what I need is to modify the previous query …

> self select: [ :each | each clientTypes isEmpty]

… by negating it. I tried

> self select: [ :each | each clientTypes not isEmpty]

but that didn't work. Then I tried `isNotEmpty`, and it did work. But it should be mentioned in the step-by-step guide, since the risk of losing a potential user is pretty high at this stage.

I was also surprised that Ctrl+Space doesn't give me an autocompletion. That's what I'm used to from Eclipse, IntelliJ and similar tools. And since there is syntax highlighting, I'm definitely using a little more than a plain text editor here. For a system that is about exploring and discovering, autocompletion is a must-have.

----

In the same manual, there is a paragraph:

> Select the whole text

Selecting the whole text is not necessary. I could press Ctrl+G without having anything selected, and it worked.

**Comment by girba** [comment]
The picture underneath the sentence shows you the code (using `notEmpty`).

Autocompletion works with `tab` in the default installation.
