### ISSUE TITLE
"Moose helper" window should link to The Moose Book

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1279]
The "Moose helper" consists of only 4 small documents that don't provide much help. A much better resource is The Moose Book. Therefore, the "Moose helper" should link to that book.

I opened the "Moose helper" window because I was looking for an overview of all keyboard shortcuts. I already discovered the following:

* Ctrl+Space does nothing (I expected autocompletion)
* Alt+Space selects the current word
* Shift+Space opens a search dialog (very nice)

There are probably many more shortcuts available. The list of these shortcuts should be easily accessible.

**Comment by Ducasse** [comment]
I suggest to remove all the helper documents and just put a link to the moose book. We should not have duplicated documentation.

**Comment by badetitou** [comment]
see #1441
