### ISSUE TITLE
Usability: pressing Ctrl+G selects whole text, it shouldn't do that

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1280]
When I press Ctrl+G in a playground tab, the whole text is selected and then executed. This gets in my way of working efficiently.

I have the following text, taken from the tutorial:

> self select: [ :each | each isAnnotatedWith: 'Deprecated' ]

The text cursor is inside the `isAnnotatedWith` word since I want to explore this and some other predicates. When I press Ctrl+G now to see the result, the whole text is selected and the text cursor is placed at the end of the text.

This is inconvenient because my next plan was to replace the word `isAnnotatedWith` with another word. To do this I have to navigate now instead of simply pressing Alt+Space and overwriting the current word.

**Comment by girba** [comment]
If you only want to execute the current line, you can press Ctrl+g.

I understand the issue, but this behavior will not change in the current tools. This behavior will be revisited in the new Glamorous Toolkit that is currently under work.
