### ISSUE TITLE
Moose Panel: orange corner in the upper right is not explained

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1281]
In the text areas of Moose Panel, there is an orange corner:

![image](https://user-images.githubusercontent.com/3233724/35186944-c0c5b628-fe1c-11e7-9bc3-0afc2ab287e8.png)

Hovering over the corner with the mouse doesn't give me a tooltip. There's also no other explanation.

First I thought it would mark the currently active editor, but that's wrong because I have two editor windows and both have the orange marker.

**Comment by Ducasse** [comment]
This is part of Pharo. This shows that the text is not saved.

**Comment by JankoKorelc** [comment]
When complaining about the orange marker it shall be noticed such marker is
resul of pinkish shadow and errror
