### ISSUE TITLE
Moose Panel: selecting text requires positioning the mouse cursor precisely

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1282]
![image](https://user-images.githubusercontent.com/3233724/35186961-24d0cca2-fe1d-11e7-8aeb-f1696367f19d.png)

In the above image I want to select the whole text using the mouse. To do this I click on the middle of the white area and then drag the mouse cursor beyond the upper left corner of the text field.

But the text is not selected. To actually select it I have to click somewhere on the last line of the text. It should be possible to click anywhere in the text field. This is common behavior in many editors (Google Chrome, IntelliJ, Microsoft Notepad).

**Comment by Ducasse** [comment]
I do not really get it. Now this is not a moose issue but a Pharo one. 
There are several ways to select text in Pharo and may be there are not working but many people are using it. So please report there.
