### ISSUE TITLE
Moose Panel: long-lasting computations take place in the UI thread

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1283]
1. Open the ArgoUML example project
2. Right click on "All model classes"
3. Select Visualize > System Attraction

A computation starts and the whole window becomes unresponsive. The computation takes longer than one minute, and during this time, the application is completely unusable. It is not even possible to see how long the computation will take or to cancel it. The only way out is to quit the Pharo VM.

**Comment by girba** [comment]
Thanks. This is a known issue. We are working on a new UI stack, called Bloc, that offers new kind of options. With the current infrastructure, we can't manage much.

You can always interrupt an execution using `Ctrl+.`.

**Comment by rillig** [comment]
> You can always interrupt an execution using `Ctrl+.`.

Unfortunately, I cannot.

I ran the RTMondrian force code on "All model classes (2385)", which gave me plenty of time to interrupt the task. But neither pressing `Ctrl+.` or clicking on the cancel icon in the progress bar of the "Laying out elements" didn't stop anything. The whole Pharo window was frozen, I also could not open the World menu.

![image](https://user-images.githubusercontent.com/3233724/35187667-c59592c6-fe27-11e7-843c-34a38c41c70a.png)

**Comment by girba** [comment]
Can you try with `Alt + .`? Pharo has issues with shortcuts on Windows.

**Comment by rillig** [comment]
Thanks, with `Alt+.` it worked.
