### ISSUE TITLE
Moose Panel editor: automatic quotation mark insertion prevents natural typing

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1284]
In a playground editor of the Moose Panel, when I type the following text blindly, without looking at the screen:

> self select: [ :each | each isAnnotatedWith: 'Deprecated' ]

I end up with the following text in the editor:

> self select: [  :each | each isAnnotatedWith: 'Deprecated' ]' ]

There are two differences:

* There is an extra space before the `:each`. Not important.
* The quotation mark after `Deprecated` is duplicated. This is important since it is a syntax error.
* The closing bracket is duplicated. This is important since it is a syntax error.

When the editor tries to be intelligent by automatically inserting characters, it should also detect when the matching characters are typed manually and then merge them. This is possible since both Eclipse and IntelliJ do exactly this, successfully.

**Comment by girba** [comment]
This behavior is called `Smart Characters`. I agree that they are not ideal, and they can be disabled via the settings. Click on the background, `System/Settings`, then search for `Smart`, press Enter, and you can disable `Smart Characters`.
