### ISSUE TITLE
Moose Panel: clipboard doesn't work

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1286]
When I open a playground in the Moose Panel, select all text and press Ctrl+X, the text gets removed but doesn't end up in the clipboard. Pressing Ctrl+V afterwards pastes the text that was previously in the clipboard.

Sometimes the clipboard works and sometimes it doesn't. I'm not sure about the exact circumstances.

Trying to use the clipboard with the mouse and the context menu has the exact same effect.

**Comment by girba** [comment]
What operating system are you on?

**Comment by rillig** [comment]
I'm on Microsoft Windows Version 10.0.16299.125.
I'm using the Moose 6.0 bundle from August 2016.

**Comment by girba** [comment]
Please report issues on the current development version which is Moose 6.1

**Comment by rillig** [comment]
I did report #1276, and until that one is fixed there's not much I can do. Therefore I decided to try the old version instead.

**Comment by girba** [comment]
You already got Moose 6.1 working. There is no need to load the code again. The code is already loaded. Just use the image as is.

**Comment by girba** [comment]
You likely need to use `Alt+c`, and `Alt+v`. Can you try?

**Comment by klaranosan** [comment]
Hi,

we tried the commands many times in Moose 6.1 on Windows 10 and found no problems with cutting and pasting the text. To be able to reproduce this bug more information needs to be given (the circumstances).

Team opendev.

**Comment by rillig** [comment]
I tested it again, and it works perfectly in Moose 6.1.
