### ISSUE TITLE
The Moose Book: section "Analyzing Java code" ends abruptly

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1287]
http://themoosebook.org/book/index.html#h3navigatingxmlfiles

The last sentence above this heading reads:

> For example, an interesting candidate to investigate is the one class that uses two deprecated ones.

This sentence sounds as if the step-by-step instructions are continuing and in order to investigate this interesting candidate, we need to look at XML files first and then come back to this topic. But this isn't the case. The section just ends here, which left me confused.

The section should have some closing words so that readers know it's over. These closing words could mention that the "Moose Panel" can be closed now since it won't be used in the following sections.

**Comment by Ducasse** [comment]
This should be taken into account by the new version of the moosebook available at https://github.com/SquareBracketAssociates/MasteringMoose

**Comment by badetitou** [comment]
Can we move this issue?

**Comment by badetitou** [comment]
issue moved
