### ISSUE TITLE
Parsed XML data shows confusing icon for numbers

### ISSUE THREAD

**Issue by rillig** [moosetechnology/Moose#1288]
![image](https://user-images.githubusercontent.com/3233724/35187798-16447226-fe2a-11e7-904e-3dbcefd1ff10.png)

The numbers in this screenshot are marked with a capital sigma. This is confusing at first because the capital sigma [stands for a sum](https://en.wikipedia.org/wiki/Sigma#Upper-case), which is a very special kind of number. So I thought: "Why would the XML version field be a sum?"

The icon should be changed into something else representing numbers. I see that using a specific digit like 0 could be too confusing. But maybe it's acceptible when the number is circled or put into a rounded square.

**Comment by girba** [comment]
You are looking at the default object inspector view used in Pharo. This is an icon used in Pharo and it will not change within the context of Moose.
