### ISSUE TITLE
[Glamour] several examples are broken or misbehaving

### ISSUE THREAD

**Issue by peteruhnak** [moosetechnology/Moose#1290]
(all from Glamorous Example Browser)

* **Tree with menu**, and possibly others have this kind of bug (I guess the API changed along the way)
```smalltalk
selectionAct: [:tree | tree inspect ] on: $i entitled: 'Inspect';
```
but it should be
```smalltalk
selectionAct: [ :presentation :tree | tree inspect ] on: $i entitled: 'Inspect';
```
* **Spawn browser actions** doesn't seem to do anything
* **Magritte presentation** fails even if I have magritte installed, which is a bit annoying because then the user has to close the Glamorous Browser and open again
* **Two inter-dependent panes** seems to misbehave too (clicking on the second pane removes both and leaves me with empty window)(edited)
* **Toolbar** doesn't show the toolbar inside Glamorous Browser, but running it from playground works as expected

**Comment by badetitou** [comment]
We will kill Glamour.
So I tag with old-glamour and say goodbye to the issue.
(since nobody will fix it...)
