### ISSUE TITLE
Iceberg Left in Broken State

### ISSUE THREAD

**Issue by seandenigris** [moosetechnology/Moose#1291]
In a fresh Moose 6.1 image dl-ed via Launcher, Iceberg lists several repositories which all seem to be broken. This leads to problems when loading code that depends on those repos. In contrast, in Pharo 6.1, Iceberg shows no repositories. Maybe there should be a `IceRepository reset` at the end of the Moose build?

**Comment by girba** [comment]
Thanks for looking into this.

**Comment by girba** [comment]
Fixed

**Comment by seandenigris** [comment]
Confirmed! Latest DL via Launcher has clean Iceberg. Thanks :)
