### ISSUE TITLE
Add links to the original package sources

### ISSUE THREAD

**Issue by pavel-krivanek** [moosetechnology/Moose#1313]
The BaselineOfMoose should contain information about the original package sources

**Comment by jecisc** [comment]
DeepTraverser: https://github.com/pharo-contributions/DeepTraverser
Mocketry: https://github.com/dionisiydk/Mocketry
StateSpecs: https://github.com/dionisiydk/StateSpecs

I'll try to add the links to this issue when I encounter dependencies during my work.

**Comment by pavel-krivanek** [comment]
git@github.com:moosetechnology/Glamour.git
git@github.com:feenkcom/gtoolkit-examples.git

**Comment by jecisc** [comment]
Moose algos: https://github.com/moosetechnology/MooseAlgos

**Comment by jecisc** [comment]
RoelTyper: https://github.com/RMODINRIA/RoelTyper

**Comment by jecisc** [comment]
Ring2: https://github.com/pavel-krivanek/Ring2

**Comment by jecisc** [comment]
CollectionExtensions: https://github.com/pharo-contributions/CollectionExtensions

**Comment by jecisc** [comment]
We don't need to sync anymore. This is now useless.
