### ISSUE TITLE
Famix should not depend on Roassal and Glamour

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1368]

**Comment by pavel-krivanek** [comment]
what Famix packages?

**Comment by jecisc** [comment]
Famix-Support.

**Comment by pavel-krivanek** [comment]
Well, the FamixTraitGroupDescription should not be a trait. It is a relic of its past use. This class creates the   UI browser of Trait groups and the dependency on Roassal and Glamour is not accidental. We just need to use better names for the class and package and make it more standalone

**Comment by pavel-krivanek** [comment]
I have seen your PR. Good.
