### ISSUE TITLE
FamixTClassHierarchyNavigation depends on FamixTWithTypeAliases

### ISSUE THREAD

**Issue by pavel-krivanek** [moosetechnology/Moose#1406]
FamixTClassHierarchyNavigation depends on FamixTWithTypeAliases

FamixTClassHierarchyNavigation>>#allSubclassesDo: calls self typeAliases

**Comment by pavel-krivanek** [comment]
FamixTClassHierarchyNavigation>>#withSubclassHierarchy calls allTypeAliases

**Comment by badetitou** [comment]
It has been killed in https://github.com/moosetechnology/Moose/commit/500f520
Can we close this issue?
