### ISSUE TITLE
Distribution map does not honorate elements title configuration

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Moose#1413]
we cannot customize the title of an element

**Comment by anneetien** [comment]
renderOn: view
	| parts partElements shape |
	parts := self orderParts: self parts.
	shape := RTCompositeShape new.
	shape add: (RTLabel new text: (self elementTitleBlock); height: 10; color: Color black).
	shape add: (RTBox new color: Color transparent; borderColor: Color gray).
	partElements := shape elementsOn: parts.
	partElements do: [ :each |
		| elements |
		view add: each.
		elements := self renderElementsFrom: each model on: view. 
		view addAll: elements.
		RTGridLayout on: elements.
		RTNest new
			on: each
			inShape: #second 
			nest: elements.	 ].
	RTGridLayout on: partElements.
	partElements @ RTDraggable

**Comment by anneetien** [comment]
The code above is a fix for the AbstractDistributionMap

**Comment by Ducasse** [comment]
We do not know yet how to commit

**Comment by Ducasse** [comment]
We will try to do a PR with anne 
Stef
