### ISSUE TITLE
Moose crashes when running through the moose book tutorial

### ISSUE THREAD

**Issue by rkreg** [moosetechnology/Moose#1423]
When trying to complete the tutorial from [The Moose Book](http://themoosebook.org/book/index.html), the whole Pharo window crashes. It's possible this is an issue with Pharo - I'm simply running the Pharo.exe that comes embedded in the moose_suite_6_1-win-64 (which is the currently-linked distribution for [installing Moose](http://moosetechnology.org/#install) on 64-bit Windows).

As soon as I get to the part of the tutorial where I'm supposed to visualize the data (as shown in the screenshot below), the entire pharo window simply closes. 

![image](https://user-images.githubusercontent.com/1205439/50226806-6607a980-0361-11e9-9bc2-2db3005a2937.png)

I'd love to provide some extra details, but I don't see any logs or anything describing what's going on, and I'm pretty new to Pharo and Moose in general, so I'm unsure what troubleshooting steps to take. If anyone has some steps I can follow to provide better information, I'd be happy to do so. I'll also go ahead and provide a screenshot of my moose folder post-error - as you can see, there is a stderr file present, but it's empty.
![image](https://user-images.githubusercontent.com/1205439/50229398-7884e180-0367-11e9-88a9-3c8d2d1602bc.png)

I wasn't able to attach my .mse as it was too large (45,843 KB). However, the sha-1 of the file is 375ce6bd487d27c09518003fb12706d45caf9728

Another note, it turns out that if I use the same .mse in linux, I don't run into this issue

**Comment by rkreg** [comment]
I wasn't able to get the 32-bit version to work, though I got a different error (external module not found) - My workaround was to run the linux version in virtualbox

**Comment by badetitou** [comment]
Normaly the bug has been solved.
Any other reports @rkreg  ?

**Comment by rkreg** [comment]
I'll get in and try it asap, it seems like currently site moosetechnology.org is down - when it comes back up, should I try it on the newest 64-bit version?

**Comment by badetitou** [comment]
You still can download a moose 7.0 image with the pharo launcher ( in the moose section )

It should work with both 32 and 64 bit version.

**Comment by rkreg** [comment]
Cool, I'm still waiting for the site to come back up - I'm not sure where to go to inform people that moosetechnology.org (where the Moose book links to download Moose) seems to be down

**Comment by badetitou** [comment]
A message has already been sent to the moose-dev list, it will be up soon

**Comment by rkreg** [comment]
I didn't originally understand what you meant about the pharo launcher, but I just figured it out :)

And yes, it appears that the problem is solved and I can pull up images with Mondrian now! Interestingly, it's MUCH slower than on my linux vm (running viewDependenciesWithCycles on the same dataset takes ~30 seconds on Windows and ~1.5 seconds on a linux vm), but it totally works 👍

**Comment by rkreg** [comment]
Awesome, thank YOU! Let me know if there's anything I can do to help diagnose things, I'm still fairly new to Pharo but I'm starting to kinda figure it out, and I wouldn't at all mind helping out if I can :)
