### ISSUE TITLE
Can't view sources in Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by rkreg** [moosetechnology/Moose#1424]
When following the [Moose book tutorial](url), at the step that says:
 `Just to make sure that we indeed got deprecated classes, let's investigate one of them and select to view the source code.`

I get the exception `#new was sent to nil`:
![image](https://user-images.githubusercontent.com/1205439/51045844-d3ce7c00-1581-11e9-8064-77a626c74840.png)
Here's a shot with a little more context about what step I'm trying to follow:
![image](https://user-images.githubusercontent.com/1205439/51046431-45f39080-1583-11e9-9a87-2436dd02e86b.png)

I seem to get the issue whenever I try to view the source of any class, regardless of how I try to get there.

Here's my version information. 
![image](https://user-images.githubusercontent.com/1205439/51045463-e5635400-1580-11e9-83e4-504fd48b473f.png)
I am running in virtualbox, which I wouldn't think should matter, but maybe 🤷‍♂️ 

Here are the versions everything I'm using from the tutorial:
![image](https://user-images.githubusercontent.com/1205439/51045599-3a06cf00-1581-11e9-848a-7d2cb1c9a363.png)

It also might be worth noting that when creating the .mse, there were quite a few problems - there's a 2 MB .problems file. I can try to attach that if needed, though I'm not sure if Github will allow it.

I'm still super new to Moose, so I'm not sure if there's additional helpful information I can provide - let me know if there is and I'll update the issue 😃

**Comment by rkreg** [comment]
This also appears to be a problem in Windows. I think I'm also correctly following the step to set the root folder, but that doesn't appear to make any difference.

**Comment by NoamRamonet** [comment]
Same problem in Mac OS. There is no difference setting up the root folder to ArgoUml-0-34 (as expressed in the tutorial) or  ArgoUml-0-34/src

**Comment by girba** [comment]
Are you using Moose 6.1?

**Comment by badetitou** [comment]
The bug has been fixed in Moose 7.0
I do not know on Moose 6.1

I can not reproduce the bug on windows
