### ISSUE TITLE
MooseBook: Manage windows in the tutorial

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1426]
The tutorial of the Moosebook ask to generate a .mse file via jdt to famix but to do that there is only a .sh file.

This is not windows friendly and an extra set of instructions explaining how to run it in windows would be great. 

Section: http://www.themoosebook.org/book/index.html#h2mooseinaction

**Comment by girba** [comment]
That is not quite true. The jdt2famix distribution comes with a `.cmd` file:
https://github.com/feenkcom/jdt2famix/releases/download/1.0.12/jdt2famix-bin-1.0.12.zip

**Comment by rkreg** [comment]
Oh interesting, I didn't notice that - it would be cool if the Moose book mentioned that file, I just went in and read the .sh file and ended up manually running java from the command line to generate the .mse

**Comment by rkreg** [comment]
I just checked and the download to jdt2famix that the Moose book links to does not contain a .cmd file - I'm referring to the part of the book that says:

> Download and unzip version 1.0.2.

**Comment by badetitou** [comment]
I think we should update the Moose book to download the version 1.0.12 and not 1.0.2

**Comment by badetitou** [comment]
I've opened a pull request there: https://github.com/girba/themoosebook/pull/10
