### ISSUE TITLE
Improve API for setting factories

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1429]
With the recent changes we need to set a facotry while using MoosePharoImporterTask.

Compatibility:

```Smalltalk
MoosePharoImporterTask new
	factory: SmalltalkCompatibilityMetamodelFactory
```

Smalltalk model:

```Smalltalk
MoosePharoImporterTask new
	factory: SmalltalkMetamodelFactory
```

We could improve this API. 

For example, we could add methods like #forSmalltalkCompotibility and #forSmalltalk.

**Comment by Ducasse** [comment]
Tx
I will
- deprecate factory to factoryClass
- and set the factory class to SmalltalkCompatibilityMetamodelFactory by default for the MoosePharoImporterTask.

**Comment by jecisc** [comment]
I october last year I fixed that. Now we do not need to set any factory since it is the model that will give the right factory to the importer.
