### ISSUE TITLE
self metamodel is not equal to self class metamodel

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Moose#1446]
Import in a MoosePanel the Collections package of Pharo to have a Pharo model.
Go on the FamixStClass Collection and ask it: self queryAllIncoming. There are no answer whereas it is written that there are three references.

If you go deeper into details, you see that on the FamixStClass Collection self childrenSelectors returns an empty collection.

One step further, it is because self class metamodel != self metamodel.

**Comment by badetitou** [comment]
The bug is solved, see #1448
