### ISSUE TITLE
MetaModel incorrect when we have a metamodel that extends a second one

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Moose#1454]
To compute the metamodel, an entity will ask to the root of the metamodel what is the metamodel

So, all the root elements will define something like

```st
metamodel

	<generated>
	^ (self class environment at: #FASTJavaMetamodelGenerator) metamodel
```

But in case we have a metamodel that extends a second one. None of the entities of the first metamodel is considered as a root. So, they do not implement `metamodel`.

So their metamodel are considered as the metamodel of the second metamodel. (so many metamodel :/)

So, we may implement the `metamodel` model in the main metamodel (first) root elements.

**Comment by mahugnon** [comment]
Fixed

**Comment by mahugnon** [comment]
fixed see with benoit
