### ISSUE TITLE
To represent an AST we can not represent potential multiple container 

### ISSUE THREAD

**Issue by hogoww** [moosetechnology/Moose#1463]

**Comment by hogoww** [comment]
Issue opened by @badetitou 
A solution given by @juliendelplanque : 

container1/2 contained & containmentTrait are instances variable of the builder you're using.

"in defineClasses"
container1 := builder newClassNamed:#Containe1.
container2 := builder newClassNamed:#Container2.
contained := builder newClassNamed:#Contained.

containmentTrait:= builder newTraitNamed:#ContainmentTrait.

"in define relations"
(containmentTrait property:#childs) <>- (contained property:#parent).

"In defineHierarchy"
container1 --|> containmentTrait.
container2 --|> containmentTrait.

**Comment by badetitou** [comment]
The solution does work only if we use a simple metamodel, 
But we cannot use this solution when we have linked metamodels (because we can not create extension Trait)

**Comment by badetitou** [comment]
In case we use multiple metamodels.
It is possible to use # withoutprimaryContainer, so the builder accept to work
But, we need to write a method to determine one container.

It is possible to define for each entity a method, or at the root, it is possible de write a generic method that looks further all the potential container and select one of them (some example in Moose-Query and FAST)
