### ISSUE TITLE
Allow to regenerate a MM without generating entries in Epicea

### ISSUE THREAD

**Issue by juliendelplanque** [moosetechnology/Moose#1468]
Else it creates a lot of mess in Epicea log making it useless and unreadable when you need to retrieve a change.

**Comment by jecisc** [comment]
If you find a method in Epicea to execute an action without logging I'm interested for other projects. Else we should implement a #executeWithoutLogging: in Epicea.

**Comment by juliendelplanque** [comment]
Maybe it is a use case for dynamic variables?

**Comment by badetitou** [comment]
Maybe we can do something like 

```st
EpMonitor current disable.
"Generate MetaModel"
EpMonitor current enable.
```

And you can add an option to the builder that config if we want to log or not the modification. By default, we do not log ?

**Comment by badetitou** [comment]
Since the method EpMonitor >> #disableDuring: is present in pharo8. 
Do we wait for Moose8 or should we implement the mehtod ?

**Comment by jecisc** [comment]
Maybe we can add a Pharo7 package with this method inside and load this package in P7 but not P8?

**Comment by badetitou** [comment]
done in #1490
