### ISSUE TITLE
Moose crash 2.3 First visualization

### ISSUE THREAD

**Issue by Bazmundi** [moosetechnology/Moose#1471]
Downloaded Moose 6.1 64 bit (released on October 24, 2018) for Windows.  Running windows.

Coded and ran 2.3 First visualization from Agile Visualization By Alexandre Bergel (Lulu press).

When example is run from either standard playground OR Moose playground you get an unhandled exception and moos IDE exits.

Same code on linux distro is fine.

**Comment by Ducasse** [comment]
Yes you should use the Moose 70 image that you can get from the pharo launcher. A VM bug has been fixed. Yes we should release a new version of Moose.

**Comment by Bazmundi** [comment]
The pharo launcher does report problems when trying to download various
images. I will stick with the linux moose image.

**Comment by badetitou** [comment]
Hello,

If needed, you still can download the last version of Moose 70 here: 
https://ci.inria.fr/moose/job/moose-7.0/lastSuccessfulBuild/artifact/moose-7.0.zip
