### ISSUE TITLE
Generating FamixNG MM using FamixGenerator is very long

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Moose#1498]
FamixGenerator generate is very long: several minutes.
The same occurs also at least for FamixPharoSmalltalkGenerator.
Investigations and approvements are required.

**Comment by jecisc** [comment]
Profiling it I see that most of the time is spent for the compilation of classes, traits and methods. I'm not sure we can improve it much...

**Comment by jecisc** [comment]
The time is divided by 5 in Pharo 8. 

For me, it went from 684sec to 131.

**Comment by badetitou** [comment]
yes, most of the time is spent in the compilation process
This problem should be assigned to pharo development
