### ISSUE TITLE
Split monolithique baseline in multiple ones with package dependencies

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1535]
Currently, we have a lot of trouble to add/remove packages because we have one big baseline and no package dependencies. 

I propose that we split that into multiple smaller baselines with package dependencies.

I'll probably begin to do it up to Famix level (because it takes time and what is higher might change with the next version of Moose)

**Comment by badetitou** [comment]
Can we say it is #1605?

**Comment by jecisc** [comment]
Done.
