### ISSUE TITLE
Moose 6 download links are broken

### ISSUE THREAD

**Issue by beatrichartz** [moosetechnology/Moose#1544]
Hi, not sure where to post this, but the Moose 6 download links are broken on the website. Also, Pharo errors with `corrupt image` when trying to pull either version 6 or 7 images from pharo launcher directly.

**Comment by badetitou** [comment]
I have reported the bug to the website repo for the link to Moose 6.1 (see https://github.com/girba/moosetechnology.org/issues/3)

I do not have the error with the Pharo Launcher with Moose 7
what do you mean by 'corrupt image'?

**Comment by badetitou** [comment]
Do you still have the error ?

**Comment by beatrichartz** [comment]
All the errors have been fixed @badetitou - thanks!
