### ISSUE TITLE
Unknown property 'hasClassScope' in FAMIXMethod

### ISSUE THREAD

**Issue by fuhrmanator** [moosetechnology/Moose#1580]
With the latest version of VerveineJ, there are messages while loading the MSE file:

> Unknown property 'hasClassScope' in FAMIXMethod

**Comment by jecisc** [comment]
Anne and Nicolas renamed some properties. 

IMO we should keep the old getter and setter with a deprecation. And possibly add a transformer to the importer to be able to automatically update wrong properties coming from a MSE. 
@badetitou your opinion?

**Comment by badetitou** [comment]
Hello,

Yes, we have to write a getter and a setter in the compatibility model (manually...) that create the link with the new name.

To create the getter and the setter. We have to create both methods and add to them the Moose pragma that said there are Famix properties (else, we still have the bug)
