### ISSUE TITLE
class withSuperclassHierarchy includes class itself?

### ISSUE THREAD

**Issue by fuhrmanator** [moosetechnology/Moose#1608]
With a Java model, I'm using `withSuperclassHierarchy` for Java Interfaces (`isInterface`) and it's returning the interface itself. That doesn't seem right:
```Smalltalk
| classes |
classes := MooseModel root first allClasses reject:#isStub.

classes do: [ :class |
    self crLog: ((class isInterface ifTrue: ['Interface: '] ifFalse: ['Class: ']) , class mooseName).
    class withSuperclassHierarchy do: [ :sc |
        self crLog: ('  Superclass: ', sc mooseName).
         ]
     ].
```
Partial output showing the problem:
```
Class: headfirst::designpatterns::factory::pizzas::PepperoniPizza
  Superclass: headfirst::designpatterns::factory::pizzas::PepperoniPizza
  Superclass: headfirst::designpatterns::factory::pizzas::Pizza
  Superclass: java::lang::Object
Interface: headfirst::designpatterns::factory::pizzaaf::Veggies
  Superclass: headfirst::designpatterns::factory::pizzaaf::Veggies
```

In fact, `withSuperclassHierarchy` also returns the class itself (even if it's not an interface). 

I'm attaching the MSE file (generated by VerveineJ) in case the problem stems from there. 
[HEAD.mse.txt](https://github.com/moosetechnology/Moose/files/3283062/HEAD.mse.txt)

**Comment by girba** [comment]
`with*` is a traversal that includes the receiver. This is the typical convention in Smalltalk. If you do not want the receiver, you can use `superclassHieararchy` instead.

**Comment by fuhrmanator** [comment]
OK - thanks for the clarification.
