### ISSUE TITLE
Test dealing with outgoingTypeDeclarations must be corrected - related to inheritsFrom:without: 

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Moose#1739]
'Test skipped following big refactor to clean FamixGenerator'.
	"outgoingTypeDeclarations is in conflict. It comes from TDependencies and TTypedStructure. inheritsFrom:without: should solve it but this fix breaks MooseQuery."

**Comment by jecisc** [comment]
I cannot find this comment anymore in the image. I suppose it was fixed and the issue was not closed.
