### ISSUE TITLE
showLevels can avoid using Transcript

### ISSUE THREAD

**Issue by Ducasse** [moosetechnology/Moose#1741]
showLevels

	^ String streamContents: [ :s | 
	self hierarchyLevels keysAndValuesDo: [ :k :v |
			s print: k.
			v do: [ :n | s nextPutAll: ' '. s print: n ].
			s cr
		]
	]

**Comment by jecisc** [comment]
This is a MooseAlgo issue, not a Moose issue (Moose algo is not managed in this repository)

**Comment by jecisc** [comment]
I'll fix this in MooseAlgo and release a v1.1.6
