### ISSUE TITLE
Why FMMultivalueLink are not ordered?

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Moose#1749]
In Famix the FMMultivalueLink are not sorted.

I suppose it is done because we want better performance? 
However, it creates some problems.

Examples:

If a method has two parameters, which one is the first one? (since parameters do not follow the original order)
When we display data, we have to sort them before displaying them. Maybe with ordered collection sorting become unnecessary.

**Comment by mahugnon** [comment]
Join to that there is a discordance. 
FMMultivalueLink is a subclass of Collection but  
`FMMultivalueLink>>species` return OrderedCollection

**Comment by mahugnon** [comment]
When I change it to OrderedCollection. It breaks other stuff
