### ISSUE TITLE
Replace #numberOfPackages by a more generic #numberOfEntityUsing:

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1807]
Currently, the Moose groups implement some methods such as numberOfPackages. 

This is specific to some entities and if we want to have that for all kind of entities it will make the API grows too much.

I propose to deprecate this one and implement a method #numberOfEntitesUsing: taking a trait as a parameter. Like this, we will be able to request all kind of entities.

**Comment by badetitou** [comment]
I agree we should add numberOfEntitiesUsing:

I don't know if we should remove numberOfPackage because it is used to add a property with the 
FMProperty: pragma

**Comment by jecisc** [comment]
IMO, the UI should be adapted to be able to show this kind of information. Because we might want to see the number of classes, of methods, of enums, of...
And I would not add one method with the pragma for each class of the MM. 

So, in the long terme I think that we should have a way to show those info without the pragma.
