### ISSUE TITLE
Refactor MooseQuery to simplify evolution

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1835]
Currently, in MooseQuery we have some API to do navigation in the containment tree or the dependencies. 

A problem I see is that for each option we add, we double the API because the API is the cartesian product of the number of options. 

This can be a limitation really fast. 

I think we should refactore MooseQuery in order to create query objects instead of all those methods.

Instead of 

```Smalltalk
entity allAtScope: FamixTClass until: [ :e | e shouldStop ]
```

```Smalltalk
(entity query all ancestors stopingWhen: [ :e | e shouldStop ]) with: FamixTClass
```

**Comment by badetitou** [comment]
I think it is done @jecisc ?

**Comment by jecisc** [comment]
Yes
