### ISSUE TITLE
Use HashTables in MooseGroupRuntimeStorage?

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1855]

**Comment by jecisc** [comment]
Why close this issue? We did not try it.

**Comment by NicolasAnquetil** [comment]
closed to clean a bit the list of issues.
It is not a bad issue in itself, but we already have many things to do and little man power.
The issue is not clear enough for somebody to take it and try it.
Could you give more details? Where to start from? What to change? ...

**Comment by jecisc** [comment]
Hashtable is a project Fame depend on to provide collection with a lookup mechanism optimized for big collections. 

Since the runtime storages are big maybe we could get performances improvements by using this project's collections in it.

Don't have any more detail since it's just an idea and I still did not check it.
