### ISSUE TITLE
Create a project MooseEnvironment 

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#1870]
Currently, in Moose, we are loading multiple projects that are not needed to build the tools in the Moose distribution but that are often useful for software analysis. 

With Benoit we think that maybe we could split Moose into two projects:
- Moose containing all the code to build the Moose tools
- MooseEnvironment that would also contain projects not used by moose but useful for the users. 

This moose environment project would contain projects such as:
- PetitParser
- SmaCC
- XMLParser
- ...

This would allow to speed up and ease the development of Moose.

For now, Benoit, Nicolas, Santi, Julien and I agree on the idea.

**Comment by fuhrmanator** [comment]
It makes sense to me. I'm guessing that releases of MooseEnvironment will specifically state which release of Moose they are based on.

**Comment by jecisc** [comment]
Yes.

Steph validated also!

**Comment by anneetien** [comment]
Hi,

I agree on the principle.
Nevertheless, would it be possible to have a clear list of which projects come where?
For example by taking Moose baseline and specifying what goes where?

Anne

**Comment by jecisc** [comment]
From what Moose contains I think we can cut into three categories:
- Projects developed in Moose
- Projects developed outside Moose but used by Moose
- Projects useful for software analysis but not used directly by Moose

**Moose projects**
- Fame
- Hashtable (But I think this one should also have a version outside Moose because it is useful)
- Famix
- KGB
- PackageBlueprint
- Reference TR
- Merlin
- MooseFinder
- Moose-RoassalPaintings
- Moose-DistributionMap


**Moose dependencies**
- Iterators (https://github.com/juliendelplanque/Iterators)
- TreeQuery (https://github.com/juliendelplanque/TreeQuery)
- Mocketry (https://github.com/dionisiydk/Mocketry)
- CollectionExtensions (https://github.com/pharo-contributions/CollectionExtensions)
- DeepTraverser (https://github.com/pharo-contributions/DeepTraverser)
- NeoCSV (https://github.com/svenvc/NeoCSV)
- RoelTyper (https://github.com/RMODINRIA/RoelTyper)
- Talents (https://github.com/tesonep/pharo-talents)
- Roassal 2 (https://github.com/ObjectProfile/Roassal2)
- Glamour (https://github.com/moosetechnology/Glamour)
- MooseAlgos (https://github.com/moosetechnology/MooseAlgos)


**Moose environment**
- PetitParser
- SmaCC
- XML Parser/Writer (still on SmalltalkHub)
