### ISSUE TITLE
FAMIXMethod>>#hasClassScope has been deprecated. Please use isClassSide instead

### ISSUE THREAD

**Issue by fuhrmanator** [moosetechnology/Moose#1875]
Trying to load an MSE file today with "Moose 8 (development version)" from today, I get a warning:
 
> Automatic deprecation code rewrite: The method FAMIXMethod>>#hasClassScope: called from FM3PropertyDescription>>#setOn:rawValue: has been deprecated. This property is deprecated from Moose 7.0. Please use isClassSide instead.
> Select Proceed to continue, or close this window to cancel the operation.

Here's what the debugger looks like:

![image](https://user-images.githubusercontent.com/7606540/65737714-6af64800-e0ad-11e9-82b9-17c64fbee19d.png)

I can select "Proceed" but the same message pops up over and over (although progress is made in loading the MSE). I'm attaching the MSE file.

**Comment by fuhrmanator** [comment]
[HFDP.mse.txt](https://github.com/moosetechnology/Moose/files/3660649/HFDP.mse.txt)

**Comment by jecisc** [comment]
I tried to reproduce it but I cannot :(

**Comment by badetitou** [comment]
I can't reproduce too :(

```
FAMIXModel importFromMSEStream: 'D:\Users\benoit.verhaeghe\Downloads\HFDP.mse' asFileReference readStream 
```

**Comment by fuhrmanator** [comment]
Here's how I load it:

```smalltalk
"Load the moose Model with some error checking"
| mseFileRef mseStream mooseModel |
mseFileRef := 'tmp/HFDP.mse' asFileReference. "Generated by FamixMaker"
mseStream := mseFileRef readStream.
mseStream
	ifNotNil: [ 
		mooseModel := MooseModel importFromMSEStream: mseStream. 
		mooseModel rootFolder:
      'tmp/MooseEasyRepos/bethrobson__Head-First-Design-Patterns'.
		mooseModel install. "So it appears in the Panel"
		mseStream close. ]
	ifNil: [ self error: 
    'Could not load MSE file into Moose: ' , mseFileRef asString ].
```

**Comment by fuhrmanator** [comment]
Is it the `MooseModel` implementation of `importFromMSEStream` that is the problem?

**Comment by jecisc** [comment]
I can reproduce now!

**Comment by fuhrmanator** [comment]
On my Pharo, the setting for **Deprecation handling > Raise a blocking dialog** was true. This is why it happens. If I turn that setting off, the problem goes away.

![image](https://user-images.githubusercontent.com/7606540/65772737-d02b5700-e108-11e9-86b8-f34f0b7dad06.png)

**Comment by fuhrmanator** [comment]
Is this bug related to https://github.com/pharo-project/pharo/pull/4539 ?

**Comment by fuhrmanator** [comment]
Thank you!
