### ISSUE TITLE
Rename Tests packages

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Moose#1876]
We should rename the Tests packages with the "Tests" at the end

Moose-Tests-Core -> Moose-Core-Tests
Moose-Tests-Finder -> Moose-Finder-Tests
etc.

**Comment by jecisc** [comment]
There is already an issue for this. 
And I waited to finish to integrate Anne’s PR to do that to avoid conflicts.

**Comment by badetitou** [comment]
Ah yes... It's my issue 
#1763

**Comment by jecisc** [comment]
Here is a start:

https://github.com/moosetechnology/Moose/pull/2248

I did not do all of them to avoid conflict with open PRs.

**Comment by jecisc** [comment]
Some of them still need renaming.

**Comment by NicolasAnquetil** [comment]
OK, then may be list them
That way it would be easy to fix it in a sprint for example
