### ISSUE TITLE
All tests do not run and some of the missing tests are broken

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Moose#1885]

**Comment by anneetien** [comment]
Image Moose 8.0 build 141
MalGraphFixtureTest>>testGraphsRendering

**Comment by jecisc** [comment]
The problem was that someone updated the baselines without updating the Smalltalk.ston file.

So, all tests are not run.

**Comment by Ducasse** [comment]
? What is the Smalltalk.ston file?

**Comment by jecisc** [comment]
It's a file for SmalltalkCI.

By default, SmalltalkCI runs all the tests loaded from the baseline of the project. But since Moose has multiple projects inside one repository, we need to tell him the list of projects to run in the CI. And the list was not up to date.

**Comment by Ducasse** [comment]
Ahhh that file.
For travis.

**Comment by jecisc** [comment]
Fixed.
