### ISSUE TITLE
Missing dependencies when loadin Moose on CI

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Moose#1890]
For example :

> *** Warning: Warning: This package depends on the following classes:
>   MooseModelTestResourceWithSmalltalkDependency
> 
> You must resolve these dependencies before you will be able to load these definitions: 
>   FamixReferenceModelNamespaceMergingClassAndMetaclassTestResource
>  FamixReferenceModelNamespaceMergingClassAndMetaclassTestResource>>#importModel
>   FamixReferenceModelNamespaceTestResource
>   FamixReferenceModelNamespaceTestResource>>#importModel

**Comment by jecisc** [comment]
This is fixed.
