### ISSUE TITLE
Review TNamespace

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#1990]
There are 3 traits: FamixTNamespaceEntity, FamixTNamespace, and FamixTWithNamespaces
which makes it similar to an association when it is just a composition relationship: "named entities" belong to "namespace"

And the TNamed trait should be removed as a standalone trait

FamixJavaNamespace to remove

related to #1484

**Comment by pavel-krivanek** [comment]
Are you sure that this is a good idea? TNamed is for entities with a name while some metamodels do not need a real concept of a "namespace".

**Comment by NicolasAnquetil** [comment]
not completely sure, but I think if there is a name, there is some kind of namespace.
Even if the namespace is the entire system like in pharo
