### ISSUE TITLE
TWithStatements should carry a test (e.g. isBehavioural)

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#1996]
To allow testing all behaviorals easily instead of using isFunction, isMethod, ...

**Comment by NicolasAnquetil** [comment]
It should be coherent with the naming of all entities.
So maybe isWithStatements ?

**Comment by ClotildeToullec** [comment]
Questions remain:
* where do we define this test ?
We tried adding 
`((tWithStatements property: #isBehavioural type: #Boolean) comment: 'True if the entity has statements').` 
to FamixGenerator>>defineProperties
* how will it be generated ?

**Comment by jecisc** [comment]
IIRC it is possible to ask a testing selector with a different same than the original one.

**Comment by jecisc** [comment]
Fixed in https://github.com/moosetechnology/Moose/pull/2213
