### ISSUE TITLE
*-* does not create #addXYZ: methods

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#1999]
*-- seems to automatically create getter + setter + #addXYZ: method on the many side of the relation

*-* does create the getter and setter but not the #addXYZ: on both sides of the relation

**Comment by badetitou** [comment]
This PR: https://github.com/moosetechnology/Moose/pull/1878 fixes the problem
However, I dunno how I can generate the XYZ well pluralized.
Should I add the work of Oleks in the Famix dependencies? 
If not, we just have to fix the conflict and it is fixed

**Comment by jecisc** [comment]
Oleks did the pluralizer just for us for that feature :)

**Comment by badetitou** [comment]
Hmm. Ok, so I will check to integrate this with the new dependency

**Comment by badetitou** [comment]
should have been fixed by #1878
