### ISSUE TITLE
What's the real need for TScopingEntity ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#2071]
Defines only parentScope / childrenScope relationship

What is a scope ? A Namespace ? A container ?

**Comment by NicolasAnquetil** [comment]
I suggest removing this trait

**Comment by jecisc** [comment]
I would like to remove that also. We just need to be careful with how we handle this without breaking the compatibility with everything.

**Comment by anneetien** [comment]
I think Clotilde did a lot to solve this issue.
I don't know where we are.

**Comment by jecisc** [comment]
We removed the use of FamixTScopingEntity by FamixTPackage with Clotilde.

Next step is to remove them from namespaces
