### ISSUE TITLE
Create Hashtable project on pharo-contribution

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#2081]
Since Hashtable is not specific to Moose, I think we should have it also outiside Moose.

**Comment by Ducasse** [comment]
Yes it is on my todo to have it in Containers-Hashtable. 
But if you push the code there I will like it even better :)

**Comment by Ducasse** [comment]
Gees I already did it :)

https://github.com/Ducasse/Containers-HashTable

**Comment by Ducasse** [comment]
We planned to move all the containers project to a separate organisation. 
Oleks should do it. I just did not get the time.

**Comment by jecisc** [comment]
Oh, I did not know. 

Maybe there should be a synch because in Moose I added comments that are not present in the containers.

**Comment by Ducasse** [comment]
oki :)
I usually rename all the classes so you can load the package safely (except with extensions but they are rare). After I (but I do not know if I did it for this one) add more tests, revisit comments,....
Add travis (but I did not for this one argh again) :)
