### ISSUE TITLE
Models should be entities like other entities in the generator

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#2105]
Currently MooseModel are not described, they are generated behind the scene by the generators.

But may be we want to add properties to them like rootFolder, or the list of tags put on entities of the model, or the programming language of the entities in the model, ...

**Comment by badetitou** [comment]
MooseModels are created in `FamixMetamodelBuilder>>generateMooseModel`
For this to work, we should make MooseModel a Trait (to be used in the generators) and therefore, MooseAbstractGroup also

**Comment by jecisc** [comment]
I updated the title to be more explicit. 

I agree that we should have a variable in the generator representing the model and that we should be able to act on it as on any other entity.
