### ISSUE TITLE
The tag should not be implemented with private state but with a real model

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Moose#2130]
Currently, the Tags are implemented thanks to private states.
With such implementation, tags are not part of metamodels.
However, this is an important point.

So, we should consider adding the tags in a metamodel and then composed this metamodel with the others to add the tags functionality

**Comment by jecisc** [comment]
The new tag model I integrated in Moose is declared in the MM and can be query as any other entities. Thus, I think we can close this issue?
