### ISSUE TITLE
Why in Pharo, method inherits from containerEntity?

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Moose#2134]
containerEntity --|> namedEntity.
	containerEntity --|> #TWithTypes.
	containerEntity --|> #TWithClasses.
	containerEntity --|> #TWithAnnotationTypes.
	containerEntity --|> #TOODependencyQueries.

In Pharo, methods do not contain classes or types.

**Comment by jecisc** [comment]
Maybe they contains parameters?

**Comment by ClotildeToullec** [comment]
Yes, but they don't contain classes or types (in Pharo)

**Comment by anneetien** [comment]
In fact we should remove containerEntity from Pharo and Java MM.
