### ISSUE TITLE
Add common method to collect navigations

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#2157]
We have a lot of `(Pragma allNamed: #navigation: from: self to: MooseObject)` in Moose code. We should factorize it.

**Comment by anneetien** [comment]
There are 6 in MooseObject. And not always on #navigation. By what do you want to replace it?

**Comment by jecisc** [comment]
I want to have a method gathering the navigation and all Moose use this method instead of duplicating the search code everywhere.
