### ISSUE TITLE
THasImmediateSource should have TSourceAnchor by default

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Moose#2188]
Instead of adding this in a sub generator.

**Comment by anneetien** [comment]
Except if I am wrong, but currently, THasImmediateSource is used by sourceAnchor ( --|> TSourceAnchor --|> THasImmediateSource) in FamixPharoSmalltalkGenerator, but you suggest the opposite (THasImmediateSource --|> TSourceAnchor).
 What is correct?

**Comment by jecisc** [comment]
For me, the pharo source anchor should not use at all the THasImmediateSource because it is not an immediate source. It does not stock the source in the source anchor but reference a Pharo entity and get the code from it. 

In Moose 6.1 the Pharo anchor had those methods only:

FAMIXPharoAnchor
- sourceText
- pharoEntity
- pharoEntity:
- initialize
- containerFiles
- lineCount
