### ISSUE TITLE
Moose Book : ArgoUML source no longer downloadable

### ISSUE THREAD

**Issue by alanz** [moosetechnology/Moose#2226]
I don't know if this is the right place to report this issue.

The Moose Book uses ArgoUML 0.3.4 as an example, and offers a link to download it.

The tigris.org website says it is being decommissioned, but the source can still be downloaded from https://web.archive.org/web/20161118173704/http://argouml-downloads.tigris.org/nonav/argouml-0.34/ArgoUML-0.34-src.zip

Perhaps the link should be updated to that, or to some other destination.

**Comment by alanz** [comment]
And https://web.archive.org/web/20161118173429/http://argouml-downloads.tigris.org/nonav/argouml-0.34/ArgoUML-0.34-libs.zip

**Comment by Ducasse** [comment]
Thanks Alan we should probably archive in this organisation.

**Comment by mahugnon** [comment]
I downloaded ArgoUML source recently. I can put it on Github and we will redirect to it.

**Comment by sbragagnolo** [comment]
I have been checking a bit online. I have find that argouml migrated to github pages. 
The repositories have been migrated to git repositories
https://github.com/argouml-tigris-org/argouml
What i think we should do is to update the book and to have a script to download and

**Comment by sbragagnolo** [comment]
I have done a test over the version downloaded from git.

git clone https://github.com/argouml-tigris-org/argouml.git
cd argouml
"path.to\VerveineJ\verveinej.bat"   -o "path.to\Model\Argol.mse" -anchor assoc -alllocals .

And it works fine

**Comment by mahugnon** [comment]
Ok. I but don't know who have the right to modify the book

**Comment by alanz** [comment]
I am glad to see it has a home on github, and seems to be (moderately) active. I have a soft spot for that tool, from years back.  I still like the critic-based approach. And am currently pursuing it in an LSP context.

**Comment by anneetien** [comment]
It seems that this issue is no more relevant.
