### ISSUE TITLE
Optimize #hasSourceText to not read full files

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Moose#2260]
Currently #hasSourceText looks if the completeText of a FileAnchor is not empty.
```
hasSourceText
	^ self completeText isNotEmpty
```

But this is super inefficient. It will read the all text before returning true or false.
In such a case, I would except to check if the file has at least one character and I stop my research at this point.

Better, I think we should check if the "sourceText" is not empty instead of the completeText.
(so it can detect some altered file (although it should not happen)).
So, I would prefer to check if there is at least one character from "startPos" of the anchor

**Comment by jecisc** [comment]
I propose to optimize it and maybe rename it `#hasSource`? The meaning would be that for text anchor it as a string, for a Pharo anchor it has the pharo entity, for file anchor it has a non empty file, for multiple source anchor it has at least one anchor with sources?

**Comment by jecisc** [comment]
Done
