### ISSUE TITLE
TDependencyQueries>>queryOutgoingDependencies is not metamodel independant

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#2303]
implementation is:
```
queryOutgoingDependencies
	"Associations + typeDeclarations"

	^ self queryAllOutgoing
		addAll: self queryOutgoingTypeDeclarations;
		yourself
```

which means it supposes their are Type entities and Type declaration properties, ...

**Comment by NicolasAnquetil** [comment]
created #2404 for queryOutgoingTypeDeclarations

**Comment by sbragagnolo** [comment]
This method has been modified. Now the code is: 
queryAllOutgoing
	^ self query outgoing dependencies

Should we close this issue?

**Comment by anneetien** [comment]
Yes we can ;-)
