### ISSUE TITLE
Moose Technology home page out of date? Says code is on smalltalkhub…

### ISSUE THREAD

**Issue by gtackett** [moosetechnology/Moose#2314]
…as you can see in the screen clip:
![Capto_Capture 2020-09-28_05-38-34_PM](https://user-images.githubusercontent.com/52077/94488900-78a74780-01b1-11eb-9a3c-5d4a660deb84.png)

Now that smalltalkhub is a read-only archive, I assume the code actually lives elsewhere like maybe github?

There may be other parts of the home page that also need updated, but this is the only one I've run into so far.

I'm totally new, so it probably wouldn't be wise for me to try to fix anything just yet. 😁

**Comment by anneetien** [comment]
Moosetechnology is no more up to date. Please use now modularmoose.org
