### ISSUE TITLE
Some cleaning to do in models navigation (MoosePanel, MooseFinder, etc)

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Moose#2324]
- Some groups are specialized (All classes is a FamixClassGroup) and some are not (All packages is a MooseGroup).
- There are some repetitions (All classes and All FamixStClasses, that are different from All model classes)

This could probably be improved.
See ```MooseNavigationPresentation``` and ```MooseAbstractGroup>>#all...```

**Comment by anneetien** [comment]
MoosePanel and MooseFinder are no more in the image.
@ClotildeToullec I close the issue, if you need, feel free to reopen.
