### ISSUE TITLE
Latest VerveineJ (FamixNG) MSE files won't load in Moose Panel

### ISSUE THREAD

**Issue by fuhrmanator** [moosetechnology/Moose#2325]
Using the latest VerveineJ to generate MSE files, I'm unable to load with the "Import Model from MSE file" Moose Pane in the Moose Suite 8.0 (development version).  

![image](https://user-images.githubusercontent.com/7606540/103159388-e7874300-4796-11eb-8d12-210d31687961.png)

I think it's because these MSE files are not for a `MooseModel` but rather for a `FamixJavaModel`. See https://github.com/moosetechnology/Moose-Easy/issues/8

Maybe I'm jumping too far ahead, but should the Import Model function detect the type of model in the MSE file and then load it properly?

**Comment by anneetien** [comment]
@fuhrmanator normally, it works now. So I close the issue. If extra work is needed. Don't hesitate to complement.
