### ISSUE TITLE
Set meta information telling which version of Moose is loaded

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#2334]
could just be MooseVersion class with a mooseVersion method
+ an entry in the menu to show this version number
More sophisticated solution would ask GitHub

**Comment by Ducasse** [comment]
We could have a Famix.Version entity that we query from the model (to avoid to have separate meta data). 
Not sure that it is nice but we need something :).

**Comment by ClotildeToullec** [comment]
Fixed here: https://github.com/moosetechnology/Moose/pull/2390
