### ISSUE TITLE
Moose dependencies are redundant

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Moose#2349]
Moose baseline declares dependencies to projects, and some of those projects declare dependencies to one another. This results in redundancies:
![Moose-Dependencies](https://user-images.githubusercontent.com/39184695/112016559-1bbb9700-8b2d-11eb-8a6a-ed947bdd8f05.png)

No problem if all projects are in sync. It becomes tricky when we need to change the version of a project.
I'm encoutering this now: Moose 8 uses Famix:v1.x.x. No problem, all projects do.
Now Moose 9 should use Famix:development, as it *is* the dev version.
The problem is, FamixTagging and FamixReplication use Famix:v1.x.x --> Conflict.

I see those solutions, open to suggestions:
1. Remove those redundancies: if FamixTagging, FamixReplication, ... are **always** used in a Moose image (are they ??), Famix **will** be part of it, so declaring the dependency is not mandatory. However, the Famix version will depend on the Moose version.
2. Check if Famix is already loaded. Same idea as ```BaselineOfMooseEasy>>#verifyMooseInstalled```
3. A mix of the 2 above: check if Famix is already present, if not declare the dependency
4. Cheat using ```for: #(#'pharo8.x')``` and ```for: #(#'pharo9.x')```and load different versions (taking advantage of Moose versions being on different pharo versions? This is not clean and will probably create maintenance problems in the future.
5. Creating stable AND dev versions for all those projects. Very heavy just to solve this (I think it's a bad idea).

@badetitou @NicolasAnquetil @anneetien

**Comment by ClotildeToullec** [comment]
Oh, I discovered ```#customProjectAttributes```. It may help.

**Comment by badetitou** [comment]
I don't get why having a stable AND dev version for each project is a problem?
It can be only one branch if it is more convenient, but, personally, I have no problem with creating a v2 for the project that needs a v2.

If we create a Famix - v2.x.x, it means that other projects must be updated. So, v2 is logical.
If the modifications we have to make in Famix are only interned at Famix. Maybe we should move to Famix v.1.1.x, and other project does not require an update. 
I'm not a versioning expert.


So, solution 5 looks heavy, but IMO it might also help us later. If the cost is only about creating branch and tags, I go for it

**Comment by ClotildeToullec** [comment]
It is a solution but I'm not sure it makes so much sense, to have a new branch just for a different version number in the baseline. Plus 2 branches = harder to maintain.

I'm digging into it and I find that Cyril encountered this problem. This is his solution: [https://github.com/moosetechnology/FamixReplication/tree/master/src/BaselineOfFamixReplicationWithoutFamix](url). One baseline for the standalone project, one for Moose, not loading Famix.
I like that: no conditions, just declare the relevant baseline.

**Comment by NicolasAnquetil** [comment]
first: congrats for searching AND finding a similar issue. That's all the idea behind managing issues but it is not easy and we don't do it enough
second: I will agree with Benoit that branches and tags are cheap. And we must be careful with not so nice solution that can come back to bite us later on
third: I beleive I had a similar idea on the problem: why do FamixTagging depend on Famix ? Can we imagine loading it and not Famix? Can't we assume that whoever loads it will have loaded Famix too? Anyway, who loads it? Moose, so we can assume Famix is there. Some little projects do not seem to make sense outside of Moose.

**Comment by ClotildeToullec** [comment]
That was my # 1 solution. If those small projects are only used in Moose, let's remove those circular dependencies.

If someone is against it, I tested the 2-baselines solution and it seems to work.

**Comment by Ducasse** [comment]
Hello what I do on some project is that I have a baselineOf...Dev
where the dependency points to other baselineOf...Dev

Such baselines loads always the latest versions of some component. 
Then when I release. I release with BaselineOf that is not using master and bleeding edge

I do it like that to avoid to always have to edit different version of the baseline and to have conflicts between dependent version (I once had a project requires V1.0.0 of X and dev of X) and I could not load code of course because it was a conflict. 

I do it like that because git is good for version control and metacello not that good for version management (this is the object of pakbot to offer a solution but the covid killed our effort so far).

**Comment by badetitou** [comment]
I like the solution of Cyril and the Solution of Stéphane!

I agree that FamixTagging will only be present in Moose... but.. I don't know... Good versioning is important for people, killing the dependency means that we do not have good tooling (pakbot as said Stéphane?)

2 baseline is fun. It is like two branches, but inside the project (I hope it will not create problem later)

**Comment by ClotildeToullec** [comment]
Ok, so: let's have BaselineOfXYZ, declaring the dependency to Famix, and BaselineOfXYZDev (or BaselineOfXYZInMoose ? or someone has an cool name idea ?) without this dependency.

Let's keep only one branch in small projects for now. It may be necessary to create two branches at some point, I'll do it then.

I'll update ReadMe files accordingly.

**Comment by jecisc** [comment]
Personally, my fav solution would be the use of `#customProjectAttributes`. 

I had to create 2 baselines because I had a specific problem in the previous state of Moose, but this problem is not present anymore IIRC.

https://github.com/moosetechnology/moose-wiki/blob/d8a6feb3aa1b464d74df66943bfab6335425e9c7/General/DefineBaselineLoadingMoose.md

**Comment by ClotildeToullec** [comment]
Ok, I used ```customProjectAttributes```. You're right, that's probably the best way. No baseline duplication, no unnecessary branch.

Thanks all for your insights.
