### ISSUE TITLE
Clean Moose-Finder package

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Moose#2352]
There is almost no organization in this package, no common prefix, some unused classes.
To be short, there is cleaning to do.

**Comment by jecisc** [comment]
There was no cleaning because the goal was to kill it in favor of Midas

**Comment by ClotildeToullec** [comment]
Yes, no problem ! I just opened this issue as a reminder. 
Since it is not so fast to replace it completely, I need to clean a bit to know what I'm dealing with, and remove stuff slowly but surely.

**Comment by ClotildeToullec** [comment]
same as https://github.com/moosetechnology/MooseIDE/issues/193

**Comment by anneetien** [comment]
It seems that this issue is no more relevant since Moose-Finder package is no more in the image.
