### ISSUE TITLE
browser Famix entity raises an error

### ISSUE THREAD

**Issue by NourJihene** [moosetechnology/Moose#2365]
Quand on clique sur une entité et qu'on veut voir l'inspector, une erreur survient ``` selected was sent to Nil```

**Comment by anneetien** [comment]
@NourDjihan is it still relevant? Or can we close the issue?

**Comment by akevalion** [comment]
We checked the issue with @alessHosry, a new Java Famix Model was imported and the entities were inspected successfully (even the ones that are not defined - noname).

<img width="872" alt="image" src="https://user-images.githubusercontent.com/10532890/215129880-84372ebf-b674-4412-a507-f820cc9bdf90.png">
