### ISSUE TITLE
Moose Baseline could check for Pharo version

### ISSUE THREAD

**Issue by fuhrmanator** [moosetechnology/Moose#2424]
Since Moose 9 seems to require Pharo 9, the baseline could be better if it checked for Pharo 9 and then stopped if you're not running that. 

Otherwise, if you try it on Pharo 8, it goes pretty far into the process before failing when some Roassal-3 packages are missing.

**Comment by jecisc** [comment]
I think we can close because for example I'm getting Moose 11 to build on Pharo 11 and Pharo 12
