### ISSUE TITLE
Load cpp module should be the first one in the menu

### ISSUE THREAD

**Issue by akevalion** [moosetechnology/Moose#2449]
Current state
<img width="324" alt="image" src="https://user-images.githubusercontent.com/10532890/158158808-16d2ba16-7175-4adf-bdbb-f0c96858ce14.png">

Load Famix-Cpp is at end.
It should be first

**Comment by akevalion** [comment]
Update
<img width="337" alt="image" src="https://user-images.githubusercontent.com/10532890/158809603-8443d59e-87f9-4ba7-9dd1-0ec3c45c1ed9.png">

**Comment by anneetien** [comment]
FamixCPP is henceforth load by default.
