### ISSUE TITLE
Remove GT methods from Moose

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#2454]
For example: 
- MooseObject >> mooseFinderNavigationIn:
-  MooseObject >> mooseSpecificSpotterProcessorsFor:

Hints: they reference GT/Glamour classes: GLMCompositePresentation, GTFilterSubstring

or use gt methods: gtInspectorRelationsIn: , titleIcon:

**Comment by aranega** [comment]
With @anneetien we got the impression that there is no more dependencies to GT/Glamour in Moose 10, at least on `MooseObject` (`mooseFinderNavgationIn:` and `mooseSpecificSpotterProcessorsFor:` don't exist anymore there).

**Comment by anneetien** [comment]
The analysis of Moose packages dependencies shows that there is no more reference to Glamour or GT.
