### ISSUE TITLE
defaultSpec used as defaultLayout

### ISSUE THREAD

**Issue by NourJihene** [moosetechnology/Moose#2455]
In the method 'newSelectableListForPopoverExtent:' the class SpFilteringSelectableListPresenter calls for defaultLayout and this method does not exist.

![Screenshot 2022-04-22 at 22 56 15](https://user-images.githubusercontent.com/34944559/164792296-1501c688-7cce-48db-9c2e-7cfc57083df0.png)

**Comment by uNouss** [comment]
`defaultLayout` exists in `SpFilteringListPresenter`;
however I tried to create query in `Queries Browser` (`Type Query`) which is calling method `newSelectableListForPopoverExtent:` that is using `SpFilteringSelectableListPresenter defaultLayout`;
 The method was called successfully, can you elaborate more about the issue ? How the error was generated in your case ?

**Comment by ClotildeToullec** [comment]
#defaultSpec is deprecated in P10 and replaced with #defaultLayout. Which pharo version are you using?

**Comment by anneetien** [comment]
It seems that this issue is no more relevant
