### ISSUE TITLE
[Merlin] MerlinExamples not working

### ISSUE THREAD

**Issue by JanBliznicenko** [moosetechnology/Moose#2491]
Hello, I have tried multiple examples in MerlinExamples, but none of them (29 in total) seems to be working. Tried versions 9, 10 and development in Pharo 9 and 10. Is the whole Merlin project deprecated?

**Comment by ClotildeToullec** [comment]
Hello, sorry, yes it is. It is still there for legacy reasons but we are waiting for a green light to remove it. 
It stopped working after Pharo 8 and we are now using Spec 2 for all UI in Moose.

**Comment by JanBliznicenko** [comment]
Hello, thank you for your reply. Yes, I actually moved OpenPonk's usages of Merlin to Spec2 as I found out it does not work anymore :)
