### ISSUE TITLE
Number of Model entities not coherent between QueryBrowser and Inspector

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Moose#2519]
1. Load a model ( Lucene here)
2. inspect the model
3. select "Model Classes"
4. `self size` gives 3175 (see picture)
5. now back to modelBrowser, propagate the model (note: withoutStub option activated)
6. open a QueryBrowser
7. it shows 3686 classes (see picture)

![Screenshot from 2024-01-21 12-40-49](https://github.com/moosetechnology/Moose/assets/14889146/d49e9d72-58b7-4abf-9753-833c7ebf644a)

**Comment by jecisc** [comment]
I tired one a smalltalk model and I get the same number on both. I'll try on some java model now

**Comment by jecisc** [comment]
Could you provide me the lucene MSE?

I though I had it but when I try to import it, it says my model is empty after loading :/

**Comment by jecisc** [comment]
This is because #allModelClasses returns the classes and the exceptions (which are specialization of classes). But the query browser creates two entries (it does not adds the specializations to the numbers).

So I'm not sure there is an issue here
