### ISSUE TITLE
Fame should accept comments both for properties and for meta descriptions

### ISSUE THREAD

**Issue by seandenigris** [moosetechnology/Moose#708]
Originally reported on Google Code with ID 708

```
Currently, the MSEComment: is used to define comments of a property.

SomeEntity>>someProperty
  <MSEProperty: ...>
  <MSEComment: 'comment'>

This is used by the MetaBrowser but not by Fame.

At the very least, we should add a means to add MSEComment: to the class side for the
overall class.
```

Reported by `tudor.girba` on 2011-09-18 20:39:28

**Comment by girba** [comment]
Fame does not have comments as a concept. Right now, properties are commented through <MSEComment: ''> and classes are commented in the comment of the corresponding Pharo class.
