### ISSUE TITLE
Icon doesnt work with GLMStacker 

### ISSUE THREAD

**Issue by seandenigris** [moosetechnology/Moose#773]
Originally reported on Google Code with ID 773

```
Running the script:
| browser browserB|
browser := GLMTabulator new.
browser
  row: [ :r | r column: #columnA; column: #columnB ].

browser transmit to: #columnA; andShow: [ :a |
       a list display: #('Value 1' 'Value 2' 'Value 3' 'Value 1').
].

browserB:=GLMStacker new.
browserB aPane: #data; aPane: #AdditionalInformation1; aPane: #AdditionalInformation2.
browserB transmit to:#data; andShow: [ :a |
    a titleIcon: GLMUIThemeExtraIcons glamorousBrowse ;title:'Data'.
    a list display:#('data A' 'data B' 'data C').
].
browserB transmit from:#data; to:#AdditionalInformation1; andShow: [ :a |
    a titleIcon: GLMUIThemeExtraIcons glamorousAccept ;title:'Additional Information 1'.
    a text display:'something'.
].

browser transmit from: #columnA; to: #columnB; andShow: [ :a |
              a custom: browserB.
].

browser openOn: MooseModel root allModels anyOne.


the icon of the tab #AdditionalInformation1 isn't shown
```

Reported by `santiago.a.vidal` on 2012-02-01 01:51:50

**Comment by klaranosan** [comment]
Hi,

we tried running the script in Moose 6.1 and the only icon that appears is for the first tab (Data). The other two tabs (#AdditionalInformation1 and #AdditionalInformation2) still have no icon and no description.

The openDev team

**Comment by badetitou** [comment]
We will kill Glamour.
So I tag with old-glamour and say goodbye to the issue.
(since nobody will fix it...)

**Comment by seandenigris** [comment]
Hi @badetitou. This seems to be a departure from @girba's last public statement (at least that I'm aware of):
> For Glamour and existing GT, we can deal with bugs at most, but we will not invest in further development.
I think the understanding of the many users (including myself!) was that Glamour was in a maintenance phase with no new features. What does it mean that it will be "killed"? Is there a replacement library in mind to model browsers?

**Comment by jecisc** [comment]
Hi Sean,

I think that Benoît means that the next Moose interfaces will not be in Glamour, so bugs should not be reported in Moose but in te Glamour repository.
