### ISSUE TITLE
Moose should test if it runs on a vm with the freetype plugin

### ISSUE THREAD

**Issue by seandenigris** [moosetechnology/Moose#875]
Originally reported on Google Code with ID 875

```
There are several vms that don't have a working freetype plugin. This severely reduces
the number of fonts available (1 or 2 families with a very limited set of font sizes).

This is an issue for 4.6 as well as 4.7

A testcase is added in Moose-Tests-FreeType-StephanEggermont.1

```

Reported by `stephan@stack.nl` on 2012-11-26 16:32:16

<hr>
- _Attachment: [Moose-Tests-FreeType-StephanEggermont.1.mcz](https://storage.googleapis.com/google-code-attachments/moose-technology/issue-875/comment-0/Moose-Tests-FreeType-StephanEggermont.1.mcz)_

**Comment by girba** [comment]
No longer applicable
