### ISSUE TITLE
Progress bar for MSE import/export

### ISSUE THREAD

**Issue by seandenigris** [moosetechnology/Moose#93]
Originally reported on Google Code with ID 93

```
Would be nice to have a progress bar while importing or exporting a MSE.

Unfortunately it will perhaps require hacking into Fame.
```

Reported by `simon.denier` on 2009-07-20 18:02:41

**Comment by fuhrmanator** [comment]
I found that loading big MSE files still results in delays without progress. Interrupting (Alt-.) showed me that the delay is from the looping in MooseModel >>silentlyAddAll:

```SmallTalk
silentlyAddAll: entities 
	 
	entities do: [:each | self addNoAnnounce: each].
	^entities
```

My suggestion is to use `displayingProgress:` within this method.
